prompt PL/SQL Developer import file
prompt Created on quarta-feira, 29 de junho de 2016 by Administrator
set feedback off
set define off
prompt Disabling triggers for GP.TIP_TAB...
alter table GP.TIP_TAB disable all triggers;
prompt Loading GP.TIP_TAB...
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (18, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Taxas Hospitalares', 25, '3.02.01', '3.02.01', 41);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (22, 'P', 'P', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'Procedimentos e eventos em saude', 33, '2.03.02', '2.03.02', 1);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (22, 'P', 'P', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'Procedimentos e eventos em saude', 33, '3.02.01', '3.02.01', 2);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (16, 'P', 'P', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Proc. Medicos', 23, '3.02.00', '3.02.00', 21);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (5, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'Brasindice', 5, '3.02.01', '3.02.01', 22);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (5, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'Brasindice', 5, '3.02.00', '3.02.00', 61);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (18, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Taxas Hospitalares', 25, '3.02.00', '3.02.00', 62);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (19, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Proc. Materiais', 26, '3.02.00', '3.02.00', 63);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (20, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Proc. Medicamentos', 27, '3.02.00', '3.02.00', 64);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (21, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Outras Especialidades', 28, '3.02.00', '3.02.00', 65);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (22, 'P', 'P', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'Procedimentos e eventos em saude', 33, '3.02.00', '3.02.00', 66);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (19, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Proc. Materiais', 26, '3.02.01', '3.02.01', 81);
insert into GP.TIP_TAB (cdn_tabela, u##tp_tabela, tp_tabela, cod_livre_usuar_1, cod_livre_usuar_2, cod_livre_usuar_3, num_livre_usuar_1, num_livre_usuar_2, num_livre_usuar_3, val_livre_usuar_1, val_livre_usuar_2, val_livre_usuar_3, dat_livre_usuar_1, dat_livre_usuar_2, dat_livre_usuar_3, log_livre_usuar_1, log_livre_usuar_2, log_livre_usuar_3, cod_livre_1, cod_livre_2, cod_livre_3, cod_livre_4, cod_livre_5, dat_livre_1, dat_livre_2, dat_livre_3, dat_livre_4, dat_livre_5, val_livre_1, val_livre_2, val_livre_3, val_livre_4, val_livre_5, log_livre_1, log_livre_2, log_livre_3, log_livre_4, log_livre_5, num_livre_1, num_livre_2, num_livre_3, num_livre_4, num_livre_5, dat_ult_atualiz, hra_ult_atualiz, cod_usuar_ult_atualiz, nom_tab, cdn_tab_gest, u##cod_versao, cod_versao, progress_recid)
values (20, 'I', 'I', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, null, null, null, 0, 0, 0, ' ', ' ', ' ', ' ', ' ', null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, ' ', ' ', 'TUSS - Proc. Medicamentos', 27, '3.02.01', '3.02.01', 82);
commit;
prompt 13 records loaded
prompt Enabling triggers for GP.TIP_TAB...
alter table GP.TIP_TAB enable all triggers;
set feedback on
set define on
prompt Done.
