/*esse processo depende da criacao de um schema holder em separado,
para possibilitar acesso simultaneo a 2 ambientes.
DISABLE TRIGGERS FOR LOAD OF ems5.ABRAPLAN.
FOR EACH cdgrhml.ABRAPLAN NO-LOCK:
    CREATE ems5.ABRAPLAN.
    BUFFER-COPY cdgrhml.ABRAPLAN TO ems5.ABRAPLAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ABRAUNID.
FOR EACH cdgrhml.ABRAUNID NO-LOCK:
    CREATE ems5.ABRAUNID.
    BUFFER-COPY cdgrhml.ABRAUNID TO ems5.ABRAUNID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.AREA_ATUAC_GPL.
FOR EACH cdgrhml.AREA_ATUAC_GPL NO-LOCK:
    CREATE ems5.AREA_ATUAC_GPL.
    BUFFER-COPY cdgrhml.AREA_ATUAC_GPL TO ems5.AREA_ATUAC_GPL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ASSABRAN.
FOR EACH cdgrhml.ASSABRAN NO-LOCK:
    CREATE ems5.ASSABRAN.
    BUFFER-COPY cdgrhml.ASSABRAN TO ems5.ASSABRAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BOLEERRO.
FOR EACH cdgrhml.BOLEERRO NO-LOCK:
    CREATE ems5.BOLEERRO.
    BUFFER-COPY cdgrhml.BOLEERRO TO ems5.BOLEERRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BOLERPRO.
FOR EACH cdgrhml.BOLERPRO NO-LOCK:
    CREATE ems5.BOLERPRO.
    BUFFER-COPY cdgrhml.BOLERPRO TO ems5.BOLERPRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BONICABE.
FOR EACH cdgrhml.BONICABE NO-LOCK:
    CREATE ems5.BONICABE.
    BUFFER-COPY cdgrhml.BONICABE TO ems5.BONICABE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CADAMAQU.
FOR EACH cdgrhml.CADAMAQU NO-LOCK:
    CREATE ems5.CADAMAQU.
    BUFFER-COPY cdgrhml.CADAMAQU TO ems5.CADAMAQU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CAMACOMP.
FOR EACH cdgrhml.CAMACOMP NO-LOCK:
    CREATE ems5.CAMACOMP.
    BUFFER-COPY cdgrhml.CAMACOMP TO ems5.CAMACOMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CBHPMAMB.
FOR EACH cdgrhml.CBHPMAMB NO-LOCK:
    CREATE ems5.CBHPMAMB.
    BUFFER-COPY cdgrhml.CBHPMAMB TO ems5.CBHPMAMB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CBO_ESP.
FOR EACH cdgrhml.CBO_ESP NO-LOCK:
    CREATE ems5.CBO_ESP.
    BUFFER-COPY cdgrhml.CBO_ESP TO ems5.CBO_ESP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASERRO.
FOR EACH cdgrhml.CLASERRO NO-LOCK:
    CREATE ems5.CLASERRO.
    BUFFER-COPY cdgrhml.CLASERRO TO ems5.CLASERRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASHOSP.
FOR EACH cdgrhml.CLASHOSP NO-LOCK:
    CREATE ems5.CLASHOSP.
    BUFFER-COPY cdgrhml.CLASHOSP TO ems5.CLASHOSP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASMENS.
FOR EACH cdgrhml.CLASMENS NO-LOCK:
    CREATE ems5.CLASMENS.
    BUFFER-COPY cdgrhml.CLASMENS TO ems5.CLASMENS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASSE.
FOR EACH cdgrhml.CLASSE NO-LOCK:
    CREATE ems5.CLASSE.
    BUFFER-COPY cdgrhml.CLASSE TO ems5.CLASSE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMUNIC_BNFCIAR.
FOR EACH cdgrhml.COMUNIC_BNFCIAR NO-LOCK:
    CREATE ems5.COMUNIC_BNFCIAR.
    BUFFER-COPY cdgrhml.COMUNIC_BNFCIAR TO ems5.COMUNIC_BNFCIAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONDSAUD.
FOR EACH cdgrhml.CONDSAUD NO-LOCK:
    CREATE ems5.CONDSAUD.
    BUFFER-COPY cdgrhml.CONDSAUD TO ems5.CONDSAUD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONFIG_AUDIT_CAD.
FOR EACH cdgrhml.CONFIG_AUDIT_CAD NO-LOCK:
    CREATE ems5.CONFIG_AUDIT_CAD.
    BUFFER-COPY cdgrhml.CONFIG_AUDIT_CAD TO ems5.CONFIG_AUDIT_CAD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONFIG_OBRIG_ANEXO.
FOR EACH cdgrhml.CONFIG_OBRIG_ANEXO NO-LOCK:
    CREATE ems5.CONFIG_OBRIG_ANEXO.
    BUFFER-COPY cdgrhml.CONFIG_OBRIG_ANEXO TO ems5.CONFIG_OBRIG_ANEXO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONFIGUR_USUAR_PROG.
FOR EACH cdgrhml.CONFIGUR_USUAR_PROG NO-LOCK:
    CREATE ems5.CONFIGUR_USUAR_PROG.
    BUFFER-COPY cdgrhml.CONFIGUR_USUAR_PROG TO ems5.CONFIGUR_USUAR_PROG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONFIGUSUARACESSEMPRESAR.
FOR EACH cdgrhml.CONFIGUSUARACESSEMPRESAR NO-LOCK:
    CREATE ems5.CONFIGUSUARACESSEMPRESAR.
    BUFFER-COPY cdgrhml.CONFIGUSUARACESSEMPRESAR TO ems5.CONFIGUSUARACESSEMPRESAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONPRES.
FOR EACH cdgrhml.CONPRES NO-LOCK:
    CREATE ems5.CONPRES.
    BUFFER-COPY cdgrhml.CONPRES TO ems5.CONPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONTAG_BNFCIAR.
FOR EACH cdgrhml.CONTAG_BNFCIAR NO-LOCK:
    CREATE ems5.CONTAG_BNFCIAR.
    BUFFER-COPY cdgrhml.CONTAG_BNFCIAR TO ems5.CONTAG_BNFCIAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONTATO_PESSOA.
FOR EACH cdgrhml.CONTATO_PESSOA NO-LOCK:
    CREATE ems5.CONTATO_PESSOA.
    BUFFER-COPY cdgrhml.CONTATO_PESSOA TO ems5.CONTATO_PESSOA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONVPROP.
FOR EACH cdgrhml.CONVPROP NO-LOCK:
    CREATE ems5.CONVPROP.
    BUFFER-COPY cdgrhml.CONVPROP TO ems5.CONVPROP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COPRESERV.
FOR EACH cdgrhml.COPRESERV NO-LOCK:
    CREATE ems5.COPRESERV.
    BUFFER-COPY cdgrhml.COPRESERV TO ems5.COPRESERV.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DESBLOQ_BNFCIAR.
FOR EACH cdgrhml.DESBLOQ_BNFCIAR NO-LOCK:
    CREATE ems5.DESBLOQ_BNFCIAR.
    BUFFER-COPY cdgrhml.DESBLOQ_BNFCIAR TO ems5.DESBLOQ_BNFCIAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DESCPLAN.
FOR EACH cdgrhml.DESCPLAN NO-LOCK:
    CREATE ems5.DESCPLAN.
    BUFFER-COPY cdgrhml.DESCPLAN TO ems5.DESCPLAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DESCPREST.
FOR EACH cdgrhml.DESCPREST NO-LOCK:
    CREATE ems5.DESCPREST.
    BUFFER-COPY cdgrhml.DESCPREST TO ems5.DESCPREST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DESPLAUS.
FOR EACH cdgrhml.DESPLAUS NO-LOCK:
    CREATE ems5.DESPLAUS.
    BUFFER-COPY cdgrhml.DESPLAUS TO ems5.DESPLAUS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DIRET_AUTORIZ.
FOR EACH cdgrhml.DIRET_AUTORIZ NO-LOCK:
    CREATE ems5.DIRET_AUTORIZ.
    BUFFER-COPY cdgrhml.DIRET_AUTORIZ TO ems5.DIRET_AUTORIZ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DOCRECON.
FOR EACH cdgrhml.DOCRECON NO-LOCK:
    CREATE ems5.DOCRECON.
    BUFFER-COPY cdgrhml.DOCRECON TO ems5.DOCRECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DOCTO_REVIS_CTAS_COMP.
FOR EACH cdgrhml.DOCTO_REVIS_CTAS_COMP NO-LOCK:
    CREATE ems5.DOCTO_REVIS_CTAS_COMP.
    BUFFER-COPY cdgrhml.DOCTO_REVIS_CTAS_COMP TO ems5.DOCTO_REVIS_CTAS_COMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DOCTO_REVIS_CTAS_NOTA.
FOR EACH cdgrhml.DOCTO_REVIS_CTAS_NOTA NO-LOCK:
    CREATE ems5.DOCTO_REVIS_CTAS_NOTA.
    BUFFER-COPY cdgrhml.DOCTO_REVIS_CTAS_NOTA TO ems5.DOCTO_REVIS_CTAS_NOTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DOCTO_UTLZAD_COMP.
FOR EACH cdgrhml.DOCTO_UTLZAD_COMP NO-LOCK:
    CREATE ems5.DOCTO_UTLZAD_COMP.
    BUFFER-COPY cdgrhml.DOCTO_UTLZAD_COMP TO ems5.DOCTO_UTLZAD_COMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DOCUSOS.
FOR EACH cdgrhml.DOCUSOS NO-LOCK:
    CREATE ems5.DOCUSOS.
    BUFFER-COPY cdgrhml.DOCUSOS TO ems5.DOCUSOS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZCIDADE.
FOR EACH cdgrhml.DZCIDADE NO-LOCK:
    CREATE ems5.DZCIDADE.
    BUFFER-COPY cdgrhml.DZCIDADE TO ems5.DZCIDADE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZCIDPRO.
FOR EACH cdgrhml.DZCIDPRO NO-LOCK:
    CREATE ems5.DZCIDPRO.
    BUFFER-COPY cdgrhml.DZCIDPRO TO ems5.DZCIDPRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZCONCID.
FOR EACH cdgrhml.DZCONCID NO-LOCK:
    CREATE ems5.DZCONCID.
    BUFFER-COPY cdgrhml.DZCONCID TO ems5.DZCONCID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZCOTAC.
FOR EACH cdgrhml.DZCOTAC NO-LOCK:
    CREATE ems5.DZCOTAC.
    BUFFER-COPY cdgrhml.DZCOTAC TO ems5.DZCOTAC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZDECCID.
FOR EACH cdgrhml.DZDECCID NO-LOCK:
    CREATE ems5.DZDECCID.
    BUFFER-COPY cdgrhml.DZDECCID TO ems5.DZDECCID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZEMPRE.
FOR EACH cdgrhml.DZEMPRE NO-LOCK:
    CREATE ems5.DZEMPRE.
    BUFFER-COPY cdgrhml.DZEMPRE TO ems5.DZEMPRE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZESTABE.
FOR EACH cdgrhml.DZESTABE NO-LOCK:
    CREATE ems5.DZESTABE.
    BUFFER-COPY cdgrhml.DZESTABE TO ems5.DZESTABE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZESTADO.
FOR EACH cdgrhml.DZESTADO NO-LOCK:
    CREATE ems5.DZESTADO.
    BUFFER-COPY cdgrhml.DZESTADO TO ems5.DZESTADO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZFAMICBO.
FOR EACH cdgrhml.DZFAMICBO NO-LOCK:
    CREATE ems5.DZFAMICBO.
    BUFFER-COPY cdgrhml.DZFAMICBO TO ems5.DZFAMICBO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZGRUCBO.
FOR EACH cdgrhml.DZGRUCBO NO-LOCK:
    CREATE ems5.DZGRUCBO.
    BUFFER-COPY cdgrhml.DZGRUCBO TO ems5.DZGRUCBO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZGRUPOS.
FOR EACH cdgrhml.DZGRUPOS NO-LOCK:
    CREATE ems5.DZGRUPOS.
    BUFFER-COPY cdgrhml.DZGRUPOS TO ems5.DZGRUPOS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZGRUUSU.
FOR EACH cdgrhml.DZGRUUSU NO-LOCK:
    CREATE ems5.DZGRUUSU.
    BUFFER-COPY cdgrhml.DZGRUUSU TO ems5.DZGRUUSU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZIMPOSTO.
FOR EACH cdgrhml.DZIMPOSTO NO-LOCK:
    CREATE ems5.DZIMPOSTO.
    BUFFER-COPY cdgrhml.DZIMPOSTO TO ems5.DZIMPOSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZMOEDA.
FOR EACH cdgrhml.DZMOEDA NO-LOCK:
    CREATE ems5.DZMOEDA.
    BUFFER-COPY cdgrhml.DZMOEDA TO ems5.DZMOEDA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZSINCBO.
FOR EACH cdgrhml.DZSINCBO NO-LOCK:
    CREATE ems5.DZSINCBO.
    BUFFER-COPY cdgrhml.DZSINCBO TO ems5.DZSINCBO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZSUBCBO.
FOR EACH cdgrhml.DZSUBCBO NO-LOCK:
    CREATE ems5.DZSUBCBO.
    BUFFER-COPY cdgrhml.DZSUBCBO TO ems5.DZSUBCBO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DZUSUARI.
FOR EACH cdgrhml.DZUSUARI NO-LOCK:
    CREATE ems5.DZUSUARI.
    BUFFER-COPY cdgrhml.DZUSUARI TO ems5.DZUSUARI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESPECIALID.
FOR EACH cdgrhml.ESPECIALID NO-LOCK:
    CREATE ems5.ESPECIALID.
    BUFFER-COPY cdgrhml.ESPECIALID TO ems5.ESPECIALID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRSITU.
FOR EACH cdgrhml.ESTRSITU NO-LOCK:
    CREATE ems5.ESTRSITU.
    BUFFER-COPY cdgrhml.ESTRSITU TO ems5.ESTRSITU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTUNEMP.
FOR EACH cdgrhml.ESTUNEMP NO-LOCK:
    CREATE ems5.ESTUNEMP.
    BUFFER-COPY cdgrhml.ESTUNEMP TO ems5.ESTUNEMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EVENCOPP.
FOR EACH cdgrhml.EVENCOPP NO-LOCK:
    CREATE ems5.EVENCOPP.
    BUFFER-COPY cdgrhml.EVENCOPP TO ems5.EVENCOPP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EVENFATU.
FOR EACH cdgrhml.EVENFATU NO-LOCK:
    CREATE ems5.EVENFATU.
    BUFFER-COPY cdgrhml.EVENFATU TO ems5.EVENFATU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EXC_BNFCIAR_SELEC.
FOR EACH cdgrhml.EXC_BNFCIAR_SELEC NO-LOCK:
    CREATE ems5.EXC_BNFCIAR_SELEC.
    BUFFER-COPY cdgrhml.EXC_BNFCIAR_SELEC TO ems5.EXC_BNFCIAR_SELEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EXCEC_PCTE.
FOR EACH cdgrhml.EXCEC_PCTE NO-LOCK:
    CREATE ems5.EXCEC_PCTE.
    BUFFER-COPY cdgrhml.EXCEC_PCTE TO ems5.EXCEC_PCTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FLUXOFPP.
FOR EACH cdgrhml.FLUXOFPP NO-LOCK:
    CREATE ems5.FLUXOFPP.
    BUFFER-COPY cdgrhml.FLUXOFPP TO ems5.FLUXOFPP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMPAGA.
FOR EACH cdgrhml.FORMPAGA NO-LOCK:
    CREATE ems5.FORMPAGA.
    BUFFER-COPY cdgrhml.FORMPAGA TO ems5.FORMPAGA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRA_PAR.
FOR EACH cdgrhml.GRA_PAR NO-LOCK:
    CREATE ems5.GRA_PAR.
    BUFFER-COPY cdgrhml.GRA_PAR TO ems5.GRA_PAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP.
FOR EACH cdgrhml.GRP NO-LOCK:
    CREATE ems5.GRP.
    BUFFER-COPY cdgrhml.GRP TO ems5.GRP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_ESTADO_CIDAD_EXP.
FOR EACH cdgrhml.GRP_ESTADO_CIDAD_EXP NO-LOCK:
    CREATE ems5.GRP_ESTADO_CIDAD_EXP.
    BUFFER-COPY cdgrhml.GRP_ESTADO_CIDAD_EXP TO ems5.GRP_ESTADO_CIDAD_EXP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_PCTE.
FOR EACH cdgrhml.GRP_PCTE NO-LOCK:
    CREATE ems5.GRP_PCTE.
    BUFFER-COPY cdgrhml.GRP_PCTE TO ems5.GRP_PCTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_TRANS.
FOR EACH cdgrhml.GRP_TRANS NO-LOCK:
    CREATE ems5.GRP_TRANS.
    BUFFER-COPY cdgrhml.GRP_TRANS TO ems5.GRP_TRANS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRUPPRES.
FOR EACH cdgrhml.GRUPPRES NO-LOCK:
    CREATE ems5.GRUPPRES.
    BUFFER-COPY cdgrhml.GRUPPRES TO ems5.GRUPPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIAADIC.
FOR EACH cdgrhml.GUIAADIC NO-LOCK:
    CREATE ems5.GUIAADIC.
    BUFFER-COPY cdgrhml.GUIAADIC TO ems5.GUIAADIC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIA_AUTORIZ_COMP.
FOR EACH cdgrhml.GUIA_AUTORIZ_COMP NO-LOCK:
    CREATE ems5.GUIA_AUTORIZ_COMP.
    BUFFER-COPY cdgrhml.GUIA_AUTORIZ_COMP TO ems5.GUIA_AUTORIZ_COMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIA_DIRET.
FOR EACH cdgrhml.GUIA_DIRET NO-LOCK:
    CREATE ems5.GUIA_DIRET.
    BUFFER-COPY cdgrhml.GUIA_DIRET TO ems5.GUIA_DIRET.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIA_HIS.
FOR EACH cdgrhml.GUIA_HIS NO-LOCK:
    CREATE ems5.GUIA_HIS.
    BUFFER-COPY cdgrhml.GUIA_HIS TO ems5.GUIA_HIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIA_INFO_PREST.
FOR EACH cdgrhml.GUIA_INFO_PREST NO-LOCK:
    CREATE ems5.GUIA_INFO_PREST.
    BUFFER-COPY cdgrhml.GUIA_INFO_PREST TO ems5.GUIA_INFO_PREST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GUIAUTOR.
FOR EACH cdgrhml.GUIAUTOR NO-LOCK:
    CREATE ems5.GUIAUTOR.
    BUFFER-COPY cdgrhml.GUIAUTOR TO ems5.GUIAUTOR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_MOVIMEN_INSUMO.
FOR EACH cdgrhml.HISTOR_MOVIMEN_INSUMO NO-LOCK:
    CREATE ems5.HISTOR_MOVIMEN_INSUMO.
    BUFFER-COPY cdgrhml.HISTOR_MOVIMEN_INSUMO TO ems5.HISTOR_MOVIMEN_INSUMO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_MOVIMEN_PROCED.
FOR EACH cdgrhml.HISTOR_MOVIMEN_PROCED NO-LOCK:
    CREATE ems5.HISTOR_MOVIMEN_PROCED.
    BUFFER-COPY cdgrhml.HISTOR_MOVIMEN_PROCED TO ems5.HISTOR_MOVIMEN_PROCED.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HORAURGE.
FOR EACH cdgrhml.HORAURGE NO-LOCK:
    CREATE ems5.HORAURGE.
    BUFFER-COPY cdgrhml.HORAURGE TO ems5.HORAURGE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INNCOBPR.
FOR EACH cdgrhml.INNCOBPR NO-LOCK:
    CREATE ems5.INNCOBPR.
    BUFFER-COPY cdgrhml.INNCOBPR TO ems5.INNCOBPR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INSUGUIA.
FOR EACH cdgrhml.INSUGUIA NO-LOCK:
    CREATE ems5.INSUGUIA.
    BUFFER-COPY cdgrhml.INSUGUIA TO ems5.INSUGUIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INSUMO_GUIA_COMP.
FOR EACH cdgrhml.INSUMO_GUIA_COMP NO-LOCK:
    CREATE ems5.INSUMO_GUIA_COMP.
    BUFFER-COPY cdgrhml.INSUMO_GUIA_COMP TO ems5.INSUMO_GUIA_COMP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEMPLAN.
FOR EACH cdgrhml.ITEMPLAN NO-LOCK:
    CREATE ems5.ITEMPLAN.
    BUFFER-COPY cdgrhml.ITEMPLAN TO ems5.ITEMPLAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LAYOUTEI.
FOR EACH cdgrhml.LAYOUTEI NO-LOCK:
    CREATE ems5.LAYOUTEI.
    BUFFER-COPY cdgrhml.LAYOUTEI TO ems5.LAYOUTEI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LOCAATEN.
FOR EACH cdgrhml.LOCAATEN NO-LOCK:
    CREATE ems5.LOCAATEN.
    BUFFER-COPY cdgrhml.LOCAATEN TO ems5.LOCAATEN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LOCAAUTO.
FOR EACH cdgrhml.LOCAAUTO NO-LOCK:
    CREATE ems5.LOCAAUTO.
    BUFFER-COPY cdgrhml.LOCAAUTO TO ems5.LOCAAUTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LOCAPROD.
FOR EACH cdgrhml.LOCAPROD NO-LOCK:
    CREATE ems5.LOCAPROD.
    BUFFER-COPY cdgrhml.LOCAPROD TO ems5.LOCAPROD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MENSAUTO.
FOR EACH cdgrhml.MENSAUTO NO-LOCK:
    CREATE ems5.MENSAUTO.
    BUFFER-COPY cdgrhml.MENSAUTO TO ems5.MENSAUTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MENSCART.
FOR EACH cdgrhml.MENSCART NO-LOCK:
    CREATE ems5.MENSCART.
    BUFFER-COPY cdgrhml.MENSCART TO ems5.MENSCART.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MENSISTE.
FOR EACH cdgrhml.MENSISTE NO-LOCK:
    CREATE ems5.MENSISTE.
    BUFFER-COPY cdgrhml.MENSISTE TO ems5.MENSISTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MODADMIN.
FOR EACH cdgrhml.MODADMIN NO-LOCK:
    CREATE ems5.MODADMIN.
    BUFFER-COPY cdgrhml.MODADMIN TO ems5.MODADMIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MODALID.
FOR EACH cdgrhml.MODALID NO-LOCK:
    CREATE ems5.MODALID.
    BUFFER-COPY cdgrhml.MODALID TO ems5.MODALID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOD_COB.
FOR EACH cdgrhml.MOD_COB NO-LOCK:
    CREATE ems5.MOD_COB.
    BUFFER-COPY cdgrhml.MOD_COB TO ems5.MOD_COB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MODEL_CONTRAT.
FOR EACH cdgrhml.MODEL_CONTRAT NO-LOCK:
    CREATE ems5.MODEL_CONTRAT.
    BUFFER-COPY cdgrhml.MODEL_CONTRAT TO ems5.MODEL_CONTRAT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MODEL_PARAM_PROPOST.
FOR EACH cdgrhml.MODEL_PARAM_PROPOST NO-LOCK:
    CREATE ems5.MODEL_PARAM_PROPOST.
    BUFFER-COPY cdgrhml.MODEL_PARAM_PROPOST TO ems5.MODEL_PARAM_PROPOST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTCANGE.
FOR EACH cdgrhml.MOTCANGE NO-LOCK:
    CREATE ems5.MOTCANGE.
    BUFFER-COPY cdgrhml.MOTCANGE TO ems5.MOTCANGE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTIALTA.
FOR EACH cdgrhml.MOTIALTA NO-LOCK:
    CREATE ems5.MOTIALTA.
    BUFFER-COPY cdgrhml.MOTIALTA TO ems5.MOTIALTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTIV_DEMIS.
FOR EACH cdgrhml.MOTIV_DEMIS NO-LOCK:
    CREATE ems5.MOTIV_DEMIS.
    BUFFER-COPY cdgrhml.MOTIV_DEMIS TO ems5.MOTIV_DEMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTIVSOLICITSEGNDAVIA.
FOR EACH cdgrhml.MOTIVSOLICITSEGNDAVIA NO-LOCK:
    CREATE ems5.MOTIVSOLICITSEGNDAVIA.
    BUFFER-COPY cdgrhml.MOTIVSOLICITSEGNDAVIA TO ems5.MOTIVSOLICITSEGNDAVIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTVALID.
FOR EACH cdgrhml.MOTVALID NO-LOCK:
    CREATE ems5.MOTVALID.
    BUFFER-COPY cdgrhml.MOTVALID TO ems5.MOTVALID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVACGLO.
FOR EACH cdgrhml.MOVACGLO NO-LOCK:
    CREATE ems5.MOVACGLO.
    BUFFER-COPY cdgrhml.MOVACGLO TO ems5.MOVACGLO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVATGLO.
FOR EACH cdgrhml.MOVATGLO NO-LOCK:
    CREATE ems5.MOVATGLO.
    BUFFER-COPY cdgrhml.MOVATGLO TO ems5.MOVATGLO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOV_DIRET_GUIA.
FOR EACH cdgrhml.MOV_DIRET_GUIA NO-LOCK:
    CREATE ems5.MOV_DIRET_GUIA.
    BUFFER-COPY cdgrhml.MOV_DIRET_GUIA TO ems5.MOV_DIRET_GUIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVIMEN_INSUMO_NOTA.
FOR EACH cdgrhml.MOVIMEN_INSUMO_NOTA NO-LOCK:
    CREATE ems5.MOVIMEN_INSUMO_NOTA.
    BUFFER-COPY cdgrhml.MOVIMEN_INSUMO_NOTA TO ems5.MOVIMEN_INSUMO_NOTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVIMEN_PROCED_NOTA.
FOR EACH cdgrhml.MOVIMEN_PROCED_NOTA NO-LOCK:
    CREATE ems5.MOVIMEN_PROCED_NOTA.
    BUFFER-COPY cdgrhml.MOVIMEN_PROCED_NOTA TO ems5.MOVIMEN_PROCED_NOTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOV_INSU.
FOR EACH cdgrhml.MOV_INSU NO-LOCK:
    CREATE ems5.MOV_INSU.
    BUFFER-COPY cdgrhml.MOV_INSU TO ems5.MOV_INSU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVIPRES.
FOR EACH cdgrhml.MOVIPRES NO-LOCK:
    CREATE ems5.MOVIPRES.
    BUFFER-COPY cdgrhml.MOVIPRES TO ems5.MOVIPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVIPROC.
FOR EACH cdgrhml.MOVIPROC NO-LOCK:
    CREATE ems5.MOVIPROC.
    BUFFER-COPY cdgrhml.MOVIPROC TO ems5.MOVIPROC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVRCGLO.
FOR EACH cdgrhml.MOVRCGLO NO-LOCK:
    CREATE ems5.MOVRCGLO.
    BUFFER-COPY cdgrhml.MOVRCGLO TO ems5.MOVRCGLO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.NIV_PRESTDOR_TISS.
FOR EACH cdgrhml.NIV_PRESTDOR_TISS NO-LOCK:
    CREATE ems5.NIV_PRESTDOR_TISS.
    BUFFER-COPY cdgrhml.NIV_PRESTDOR_TISS TO ems5.NIV_PRESTDOR_TISS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.NOTA_FISC_PRESTDOR.
FOR EACH cdgrhml.NOTA_FISC_PRESTDOR NO-LOCK:
    CREATE ems5.NOTA_FISC_PRESTDOR.
    BUFFER-COPY cdgrhml.NOTA_FISC_PRESTDOR TO ems5.NOTA_FISC_PRESTDOR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.NOTAPRES.
FOR EACH cdgrhml.NOTAPRES NO-LOCK:
    CREATE ems5.NOTAPRES.
    BUFFER-COPY cdgrhml.NOTAPRES TO ems5.NOTAPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ORDECONS.
FOR EACH cdgrhml.ORDECONS NO-LOCK:
    CREATE ems5.ORDECONS.
    BUFFER-COPY cdgrhml.ORDECONS TO ems5.ORDECONS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ORD_REGRA_FATURAM.
FOR EACH cdgrhml.ORD_REGRA_FATURAM NO-LOCK:
    CREATE ems5.ORD_REGRA_FATURAM.
    BUFFER-COPY cdgrhml.ORD_REGRA_FATURAM TO ems5.ORD_REGRA_FATURAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ORD_REGRA_PAGTO.
FOR EACH cdgrhml.ORD_REGRA_PAGTO NO-LOCK:
    CREATE ems5.ORD_REGRA_PAGTO.
    BUFFER-COPY cdgrhml.ORD_REGRA_PAGTO TO ems5.ORD_REGRA_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ORD_VALID_FATURAM.
FOR EACH cdgrhml.ORD_VALID_FATURAM NO-LOCK:
    CREATE ems5.ORD_VALID_FATURAM.
    BUFFER-COPY cdgrhml.ORD_VALID_FATURAM TO ems5.ORD_VALID_FATURAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ORD_VALID_PAGTO.
FOR EACH cdgrhml.ORD_VALID_PAGTO NO-LOCK:
    CREATE ems5.ORD_VALID_PAGTO.
    BUFFER-COPY cdgrhml.ORD_VALID_PAGTO TO ems5.ORD_VALID_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PAPROINS.
FOR EACH cdgrhml.PAPROINS NO-LOCK:
    CREATE ems5.PAPROINS.
    BUFFER-COPY cdgrhml.PAPROINS TO ems5.PAPROINS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAFATU.
FOR EACH cdgrhml.PARAFATU NO-LOCK:
    CREATE ems5.PARAFATU.
    BUFFER-COPY cdgrhml.PARAFATU TO ems5.PARAFATU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMACP.
FOR EACH cdgrhml.PARAMACP NO-LOCK:
    CREATE ems5.PARAMACP.
    BUFFER-COPY cdgrhml.PARAMACP TO ems5.PARAMACP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMCRB.
FOR EACH cdgrhml.PARAMCRB NO-LOCK:
    CREATE ems5.PARAMCRB.
    BUFFER-COPY cdgrhml.PARAMCRB TO ems5.PARAMCRB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMECP.
FOR EACH cdgrhml.PARAMECP NO-LOCK:
    CREATE ems5.PARAMECP.
    BUFFER-COPY cdgrhml.PARAMECP TO ems5.PARAMECP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMEPP.
FOR EACH cdgrhml.PARAMEPP NO-LOCK:
    CREATE ems5.PARAMEPP.
    BUFFER-COPY cdgrhml.PARAMEPP TO ems5.PARAMEPP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMINT.
FOR EACH cdgrhml.PARAMINT NO-LOCK:
    CREATE ems5.PARAMINT.
    BUFFER-COPY cdgrhml.PARAMINT TO ems5.PARAMINT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_MOVIMEN_BNFCIAR.
FOR EACH cdgrhml.PARAM_MOVIMEN_BNFCIAR NO-LOCK:
    CREATE ems5.PARAM_MOVIMEN_BNFCIAR.
    BUFFER-COPY cdgrhml.PARAM_MOVIMEN_BNFCIAR TO ems5.PARAM_MOVIMEN_BNFCIAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMPRESTDORAUTORIZWEB.
FOR EACH cdgrhml.PARAMPRESTDORAUTORIZWEB NO-LOCK:
    CREATE ems5.PARAMPRESTDORAUTORIZWEB.
    BUFFER-COPY cdgrhml.PARAMPRESTDORAUTORIZWEB TO ems5.PARAMPRESTDORAUTORIZWEB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMRC.
FOR EACH cdgrhml.PARAMRC NO-LOCK:
    CREATE ems5.PARAMRC.
    BUFFER-COPY cdgrhml.PARAMRC TO ems5.PARAMRC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMWEB.
FOR EACH cdgrhml.PARAMWEB NO-LOCK:
    CREATE ems5.PARAMWEB.
    BUFFER-COPY cdgrhml.PARAMWEB TO ems5.PARAMWEB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAPESS.
FOR EACH cdgrhml.PARAPESS NO-LOCK:
    CREATE ems5.PARAPESS.
    BUFFER-COPY cdgrhml.PARAPESS TO ems5.PARAPESS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAVPMC.
FOR EACH cdgrhml.PARAVPMC NO-LOCK:
    CREATE ems5.PARAVPMC.
    BUFFER-COPY cdgrhml.PARAVPMC TO ems5.PARAVPMC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARTINSU.
FOR EACH cdgrhml.PARTINSU NO-LOCK:
    CREATE ems5.PARTINSU.
    BUFFER-COPY cdgrhml.PARTINSU TO ems5.PARTINSU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PCTE_GRP_PCTE.
FOR EACH cdgrhml.PCTE_GRP_PCTE NO-LOCK:
    CREATE ems5.PCTE_GRP_PCTE.
    BUFFER-COPY cdgrhml.PCTE_GRP_PCTE TO ems5.PCTE_GRP_PCTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PECONTRA.
FOR EACH cdgrhml.PECONTRA NO-LOCK:
    CREATE ems5.PECONTRA.
    BUFFER-COPY cdgrhml.PECONTRA TO ems5.PECONTRA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PEDIVREG.
FOR EACH cdgrhml.PEDIVREG NO-LOCK:
    CREATE ems5.PEDIVREG.
    BUFFER-COPY cdgrhml.PEDIVREG TO ems5.PEDIVREG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PEDVPROC.
FOR EACH cdgrhml.PEDVPROC NO-LOCK:
    CREATE ems5.PEDVPROC.
    BUFFER-COPY cdgrhml.PEDVPROC TO ems5.PEDVPROC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PERC_DEF_AUDIT.
FOR EACH cdgrhml.PERC_DEF_AUDIT NO-LOCK:
    CREATE ems5.PERC_DEF_AUDIT.
    BUFFER-COPY cdgrhml.PERC_DEF_AUDIT TO ems5.PERC_DEF_AUDIT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PERDIVPR.
FOR EACH cdgrhml.PERDIVPR NO-LOCK:
    CREATE ems5.PERDIVPR.
    BUFFER-COPY cdgrhml.PERDIVPR TO ems5.PERDIVPR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PERIMOVI.
FOR EACH cdgrhml.PERIMOVI NO-LOCK:
    CREATE ems5.PERIMOVI.
    BUFFER-COPY cdgrhml.PERIMOVI TO ems5.PERIMOVI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PER_USU.
FOR EACH cdgrhml.PER_USU NO-LOCK:
    CREATE ems5.PER_USU.
    BUFFER-COPY cdgrhml.PER_USU TO ems5.PER_USU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PLMODACO.
FOR EACH cdgrhml.PLMODACO NO-LOCK:
    CREATE ems5.PLMODACO.
    BUFFER-COPY cdgrhml.PLMODACO TO ems5.PLMODACO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTANES.
FOR EACH cdgrhml.PORTANES NO-LOCK:
    CREATE ems5.PORTANES.
    BUFFER-COPY cdgrhml.PORTANES TO ems5.PORTANES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTE_ROL_PROCED.
FOR EACH cdgrhml.PORTE_ROL_PROCED NO-LOCK:
    CREATE ems5.PORTE_ROL_PROCED.
    BUFFER-COPY cdgrhml.PORTE_ROL_PROCED TO ems5.PORTE_ROL_PROCED.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTPROC.
FOR EACH cdgrhml.PORTPROC NO-LOCK:
    CREATE ems5.PORTPROC.
    BUFFER-COPY cdgrhml.PORTPROC TO ems5.PORTPROC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PRDADM.
FOR EACH cdgrhml.PRDADM NO-LOCK:
    CREATE ems5.PRDADM.
    BUFFER-COPY cdgrhml.PRDADM TO ems5.PRDADM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PRECPROC.
FOR EACH cdgrhml.PRECPROC NO-LOCK:
    CREATE ems5.PRECPROC.
    BUFFER-COPY cdgrhml.PRECPROC TO ems5.PRECPROC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PREINPR.
FOR EACH cdgrhml.PREINPR NO-LOCK:
    CREATE ems5.PREINPR.
    BUFFER-COPY cdgrhml.PREINPR TO ems5.PREINPR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PREMOAD.
FOR EACH cdgrhml.PREMOAD NO-LOCK:
    CREATE ems5.PREMOAD.
    BUFFER-COPY cdgrhml.PREMOAD TO ems5.PREMOAD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PROPCLIN.
FOR EACH cdgrhml.PROPCLIN NO-LOCK:
    CREATE ems5.PROPCLIN.
    BUFFER-COPY cdgrhml.PROPCLIN TO ems5.PROPCLIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REATIV_BNFCIAR_CONTRAT.
FOR EACH cdgrhml.REATIV_BNFCIAR_CONTRAT NO-LOCK:
    CREATE ems5.REATIV_BNFCIAR_CONTRAT.
    BUFFER-COPY cdgrhml.REATIV_BNFCIAR_CONTRAT TO ems5.REATIV_BNFCIAR_CONTRAT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REG_ANALIS_CUST.
FOR EACH cdgrhml.REG_ANALIS_CUST NO-LOCK:
    CREATE ems5.REG_ANALIS_CUST.
    BUFFER-COPY cdgrhml.REG_ANALIS_CUST TO ems5.REG_ANALIS_CUST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REG_ANALIS_CUST_ANEXO.
FOR EACH cdgrhml.REG_ANALIS_CUST_ANEXO NO-LOCK:
    CREATE ems5.REG_ANALIS_CUST_ANEXO.
    BUFFER-COPY cdgrhml.REG_ANALIS_CUST_ANEXO TO ems5.REG_ANALIS_CUST_ANEXO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_PRESTDOR_FATURAM.
FOR EACH cdgrhml.REGRA_PRESTDOR_FATURAM NO-LOCK:
    CREATE ems5.REGRA_PRESTDOR_FATURAM.
    BUFFER-COPY cdgrhml.REGRA_PRESTDOR_FATURAM TO ems5.REGRA_PRESTDOR_FATURAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_PRESTDOR_PAGTO.
FOR EACH cdgrhml.REGRA_PRESTDOR_PAGTO NO-LOCK:
    CREATE ems5.REGRA_PRESTDOR_PAGTO.
    BUFFER-COPY cdgrhml.REGRA_PRESTDOR_PAGTO TO ems5.REGRA_PRESTDOR_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_QUANTTIVO_TECN.
FOR EACH cdgrhml.REGRA_QUANTTIVO_TECN NO-LOCK:
    CREATE ems5.REGRA_QUANTTIVO_TECN.
    BUFFER-COPY cdgrhml.REGRA_QUANTTIVO_TECN TO ems5.REGRA_QUANTTIVO_TECN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRAQUANTTIVOTECNTRANS.
FOR EACH cdgrhml.REGRAQUANTTIVOTECNTRANS NO-LOCK:
    CREATE ems5.REGRAQUANTTIVOTECNTRANS.
    BUFFER-COPY cdgrhml.REGRAQUANTTIVOTECNTRANS TO ems5.REGRAQUANTTIVOTECNTRANS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_SERV_FATURAM.
FOR EACH cdgrhml.REGRA_SERV_FATURAM NO-LOCK:
    CREATE ems5.REGRA_SERV_FATURAM.
    BUFFER-COPY cdgrhml.REGRA_SERV_FATURAM TO ems5.REGRA_SERV_FATURAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_SERV_PAGTO.
FOR EACH cdgrhml.REGRA_SERV_PAGTO NO-LOCK:
    CREATE ems5.REGRA_SERV_PAGTO.
    BUFFER-COPY cdgrhml.REGRA_SERV_PAGTO TO ems5.REGRA_SERV_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_UNIF.
FOR EACH cdgrhml.REGRA_UNIF NO-LOCK:
    CREATE ems5.REGRA_UNIF.
    BUFFER-COPY cdgrhml.REGRA_UNIF TO ems5.REGRA_UNIF.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRAUTO.
FOR EACH cdgrhml.REGRAUTO NO-LOCK:
    CREATE ems5.REGRAUTO.
    BUFFER-COPY cdgrhml.REGRAUTO TO ems5.REGRAUTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RELACDECLASAUDEPROCED.
FOR EACH cdgrhml.RELACDECLASAUDEPROCED NO-LOCK:
    CREATE ems5.RELACDECLASAUDEPROCED.
    BUFFER-COPY cdgrhml.RELACDECLASAUDEPROCED TO ems5.RELACDECLASAUDEPROCED.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REPPRESERV.
FOR EACH cdgrhml.REPPRESERV NO-LOCK:
    CREATE ems5.REPPRESERV.
    BUFFER-COPY cdgrhml.REPPRESERV TO ems5.REPPRESERV.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RESTRIC_INSUMO.
FOR EACH cdgrhml.RESTRIC_INSUMO NO-LOCK:
    CREATE ems5.RESTRIC_INSUMO.
    BUFFER-COPY cdgrhml.RESTRIC_INSUMO TO ems5.RESTRIC_INSUMO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_CAD.
FOR EACH cdgrhml.SIT_CAD NO-LOCK:
    CREATE ems5.SIT_CAD.
    BUFFER-COPY cdgrhml.SIT_CAD TO ems5.SIT_CAD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_CRE.
FOR EACH cdgrhml.SIT_CRE NO-LOCK:
    CREATE ems5.SIT_CRE.
    BUFFER-COPY cdgrhml.SIT_CRE TO ems5.SIT_CRE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SI_TE_AD.
FOR EACH cdgrhml.SI_TE_AD NO-LOCK:
    CREATE ems5.SI_TE_AD.
    BUFFER-COPY cdgrhml.SI_TE_AD TO ems5.SI_TE_AD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_PER.
FOR EACH cdgrhml.SIT_PER NO-LOCK:
    CREATE ems5.SIT_PER.
    BUFFER-COPY cdgrhml.SIT_PER TO ems5.SIT_PER.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SITPREST.
FOR EACH cdgrhml.SITPREST NO-LOCK:
    CREATE ems5.SITPREST.
    BUFFER-COPY cdgrhml.SITPREST TO ems5.SITPREST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_PRO.
FOR EACH cdgrhml.SIT_PRO NO-LOCK:
    CREATE ems5.SIT_PRO.
    BUFFER-COPY cdgrhml.SIT_PRO TO ems5.SIT_PRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SITPROME.
FOR EACH cdgrhml.SITPROME NO-LOCK:
    CREATE ems5.SITPROME.
    BUFFER-COPY cdgrhml.SITPROME TO ems5.SITPROME.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SITUCART.
FOR EACH cdgrhml.SITUCART NO-LOCK:
    CREATE ems5.SITUCART.
    BUFFER-COPY cdgrhml.SITUCART TO ems5.SITUCART.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SITUFATU.
FOR EACH cdgrhml.SITUFATU NO-LOCK:
    CREATE ems5.SITUFATU.
    BUFFER-COPY cdgrhml.SITUFATU TO ems5.SITUFATU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_USU.
FOR EACH cdgrhml.SIT_USU NO-LOCK:
    CREATE ems5.SIT_USU.
    BUFFER-COPY cdgrhml.SIT_USU TO ems5.SIT_USU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SOLICITSEGNDAVIACARTAO.
FOR EACH cdgrhml.SOLICITSEGNDAVIACARTAO NO-LOCK:
    CREATE ems5.SOLICITSEGNDAVIACARTAO.
    BUFFER-COPY cdgrhml.SOLICITSEGNDAVIACARTAO TO ems5.SOLICITSEGNDAVIACARTAO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SRIRINSS.
FOR EACH cdgrhml.SRIRINSS NO-LOCK:
    CREATE ems5.SRIRINSS.
    BUFFER-COPY cdgrhml.SRIRINSS TO ems5.SRIRINSS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SRVALIDA.
FOR EACH cdgrhml.SRVALIDA NO-LOCK:
    CREATE ems5.SRVALIDA.
    BUFFER-COPY cdgrhml.SRVALIDA TO ems5.SRVALIDA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SUBST_PRESTDOR_EXCD.
FOR EACH cdgrhml.SUBST_PRESTDOR_EXCD NO-LOCK:
    CREATE ems5.SUBST_PRESTDOR_EXCD.
    BUFFER-COPY cdgrhml.SUBST_PRESTDOR_EXCD TO ems5.SUBST_PRESTDOR_EXCD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWFUNCAO.
FOR EACH cdgrhml.SWFUNCAO NO-LOCK:
    CREATE ems5.SWFUNCAO.
    BUFFER-COPY cdgrhml.SWFUNCAO TO ems5.SWFUNCAO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWGRUPO.
FOR EACH cdgrhml.SWGRUPO NO-LOCK:
    CREATE ems5.SWGRUPO.
    BUFFER-COPY cdgrhml.SWGRUPO TO ems5.SWGRUPO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWGRUUSU.
FOR EACH cdgrhml.SWGRUUSU NO-LOCK:
    CREATE ems5.SWGRUUSU.
    BUFFER-COPY cdgrhml.SWGRUUSU TO ems5.SWGRUUSU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWLOGACESSO.
FOR EACH cdgrhml.SWLOGACESSO NO-LOCK:
    CREATE ems5.SWLOGACESSO.
    BUFFER-COPY cdgrhml.SWLOGACESSO TO ems5.SWLOGACESSO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWMODSIS.
FOR EACH cdgrhml.SWMODSIS NO-LOCK:
    CREATE ems5.SWMODSIS.
    BUFFER-COPY cdgrhml.SWMODSIS TO ems5.SWMODSIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPARAMETRO.
FOR EACH cdgrhml.SWPARAMETRO NO-LOCK:
    CREATE ems5.SWPARAMETRO.
    BUFFER-COPY cdgrhml.SWPARAMETRO TO ems5.SWPARAMETRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPERMGRP.
FOR EACH cdgrhml.SWPERMGRP NO-LOCK:
    CREATE ems5.SWPERMGRP.
    BUFFER-COPY cdgrhml.SWPERMGRP TO ems5.SWPERMGRP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPERMISSOES.
FOR EACH cdgrhml.SWPERMISSOES NO-LOCK:
    CREATE ems5.SWPERMISSOES.
    BUFFER-COPY cdgrhml.SWPERMISSOES TO ems5.SWPERMISSOES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPROGFUNCAO.
FOR EACH cdgrhml.SWPROGFUNCAO NO-LOCK:
    CREATE ems5.SWPROGFUNCAO.
    BUFFER-COPY cdgrhml.SWPROGFUNCAO TO ems5.SWPROGFUNCAO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPROGRAMA.
FOR EACH cdgrhml.SWPROGRAMA NO-LOCK:
    CREATE ems5.SWPROGRAMA.
    BUFFER-COPY cdgrhml.SWPROGRAMA TO ems5.SWPROGRAMA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWPROGRAMAS.
FOR EACH cdgrhml.SWPROGRAMAS NO-LOCK:
    CREATE ems5.SWPROGRAMAS.
    BUFFER-COPY cdgrhml.SWPROGRAMAS TO ems5.SWPROGRAMAS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWROTINA.
FOR EACH cdgrhml.SWROTINA NO-LOCK:
    CREATE ems5.SWROTINA.
    BUFFER-COPY cdgrhml.SWROTINA TO ems5.SWROTINA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWSESSAOWEB.
FOR EACH cdgrhml.SWSESSAOWEB NO-LOCK:
    CREATE ems5.SWSESSAOWEB.
    BUFFER-COPY cdgrhml.SWSESSAOWEB TO ems5.SWSESSAOWEB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWSUBROTINA.
FOR EACH cdgrhml.SWSUBROTINA NO-LOCK:
    CREATE ems5.SWSUBROTINA.
    BUFFER-COPY cdgrhml.SWSUBROTINA TO ems5.SWSUBROTINA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SWUSUARIO.
FOR EACH cdgrhml.SWUSUARIO NO-LOCK:
    CREATE ems5.SWUSUARIO.
    BUFFER-COPY cdgrhml.SWUSUARIO TO ems5.SWUSUARIO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TABLAS.
FOR EACH cdgrhml.TABLAS NO-LOCK:
    CREATE ems5.TABLAS.
    BUFFER-COPY cdgrhml.TABLAS TO ems5.TABLAS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TABTPLAS.
FOR EACH cdgrhml.TABTPLAS NO-LOCK:
    CREATE ems5.TABTPLAS.
    BUFFER-COPY cdgrhml.TABTPLAS TO ems5.TABTPLAS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPACOMD.
FOR EACH cdgrhml.TIPACOMD NO-LOCK:
    CREATE ems5.TIPACOMD.
    BUFFER-COPY cdgrhml.TIPACOMD TO ems5.TIPACOMD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_GUIA.
FOR EACH cdgrhml.TIP_GUIA NO-LOCK:
    CREATE ems5.TIP_GUIA.
    BUFFER-COPY cdgrhml.TIP_GUIA TO ems5.TIP_GUIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_IDX_REAJ.
FOR EACH cdgrhml.TIP_IDX_REAJ NO-LOCK:
    CREATE ems5.TIP_IDX_REAJ.
    BUFFER-COPY cdgrhml.TIP_IDX_REAJ TO ems5.TIP_IDX_REAJ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOCLIN.
FOR EACH cdgrhml.TIPOCLIN NO-LOCK:
    CREATE ems5.TIPOCLIN.
    BUFFER-COPY cdgrhml.TIPOCLIN TO ems5.TIPOCLIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOINSU.
FOR EACH cdgrhml.TIPOINSU NO-LOCK:
    CREATE ems5.TIPOINSU.
    BUFFER-COPY cdgrhml.TIPOINSU TO ems5.TIPOINSU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOMAQU.
FOR EACH cdgrhml.TIPOMAQU NO-LOCK:
    CREATE ems5.TIPOMAQU.
    BUFFER-COPY cdgrhml.TIPOMAQU TO ems5.TIPOMAQU.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOMEDI.
FOR EACH cdgrhml.TIPOMEDI NO-LOCK:
    CREATE ems5.TIPOMEDI.
    BUFFER-COPY cdgrhml.TIPOMEDI TO ems5.TIPOMEDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOPART.
FOR EACH cdgrhml.TIPOPART NO-LOCK:
    CREATE ems5.TIPOPART.
    BUFFER-COPY cdgrhml.TIPOPART TO ems5.TIPOPART.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOVENC.
FOR EACH cdgrhml.TIPOVENC NO-LOCK:
    CREATE ems5.TIPOVENC.
    BUFFER-COPY cdgrhml.TIPOVENC TO ems5.TIPOVENC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIPOVINC.
FOR EACH cdgrhml.TIPOVINC NO-LOCK:
    CREATE ems5.TIPOVINC.
    BUFFER-COPY cdgrhml.TIPOVINC TO ems5.TIPOVINC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_PERC.
FOR EACH cdgrhml.TIP_PERC NO-LOCK:
    CREATE ems5.TIP_PERC.
    BUFFER-COPY cdgrhml.TIP_PERC TO ems5.TIP_PERC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_PRO.
FOR EACH cdgrhml.TIP_PRO NO-LOCK:
    CREATE ems5.TIP_PRO.
    BUFFER-COPY cdgrhml.TIP_PRO TO ems5.TIP_PRO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_TAB.
FOR EACH cdgrhml.TIP_TAB NO-LOCK:
    CREATE ems5.TIP_TAB.
    BUFFER-COPY cdgrhml.TIP_TAB TO ems5.TIP_TAB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_UNI.
FOR EACH cdgrhml.TIP_UNI NO-LOCK:
    CREATE ems5.TIP_UNI.
    BUFFER-COPY cdgrhml.TIP_UNI TO ems5.TIP_UNI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_ASSOC_EVENT_SAUDE.
FOR EACH cdgrhml.TISS_ASSOC_EVENT_SAUDE NO-LOCK:
    CREATE ems5.TISS_ASSOC_EVENT_SAUDE.
    BUFFER-COPY cdgrhml.TISS_ASSOC_EVENT_SAUDE TO ems5.TISS_ASSOC_EVENT_SAUDE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISSASSOCFORMAPAGTOAPB.
FOR EACH cdgrhml.TISSASSOCFORMAPAGTOAPB NO-LOCK:
    CREATE ems5.TISSASSOCFORMAPAGTOAPB.
    BUFFER-COPY cdgrhml.TISSASSOCFORMAPAGTOAPB TO ems5.TISSASSOCFORMAPAGTOAPB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISSASSOCINSUMOACOMODA.
FOR EACH cdgrhml.TISSASSOCINSUMOACOMODA NO-LOCK:
    CREATE ems5.TISSASSOCINSUMOACOMODA.
    BUFFER-COPY cdgrhml.TISSASSOCINSUMOACOMODA TO ems5.TISSASSOCINSUMOACOMODA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_ASSOC_MOTIV_ALTA.
FOR EACH cdgrhml.TISS_ASSOC_MOTIV_ALTA NO-LOCK:
    CREATE ems5.TISS_ASSOC_MOTIV_ALTA.
    BUFFER-COPY cdgrhml.TISS_ASSOC_MOTIV_ALTA TO ems5.TISS_ASSOC_MOTIV_ALTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_ASSOC_STATUS_LOTE.
FOR EACH cdgrhml.TISS_ASSOC_STATUS_LOTE NO-LOCK:
    CREATE ems5.TISS_ASSOC_STATUS_LOTE.
    BUFFER-COPY cdgrhml.TISS_ASSOC_STATUS_LOTE TO ems5.TISS_ASSOC_STATUS_LOTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISSASSOCSTATUSSOLIC.
FOR EACH cdgrhml.TISSASSOCSTATUSSOLIC NO-LOCK:
    CREATE ems5.TISSASSOCSTATUSSOLIC.
    BUFFER-COPY cdgrhml.TISSASSOCSTATUSSOLIC TO ems5.TISSASSOCSTATUSSOLIC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_ASSOC_TIP_DESPES.
FOR EACH cdgrhml.TISS_ASSOC_TIP_DESPES NO-LOCK:
    CREATE ems5.TISS_ASSOC_TIP_DESPES.
    BUFFER-COPY cdgrhml.TISS_ASSOC_TIP_DESPES TO ems5.TISS_ASSOC_TIP_DESPES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_DENTE.
FOR EACH cdgrhml.TISS_DENTE NO-LOCK:
    CREATE ems5.TISS_DENTE.
    BUFFER-COPY cdgrhml.TISS_DENTE TO ems5.TISS_DENTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_DIAG_IMG.
FOR EACH cdgrhml.TISS_DIAG_IMG NO-LOCK:
    CREATE ems5.TISS_DIAG_IMG.
    BUFFER-COPY cdgrhml.TISS_DIAG_IMG TO ems5.TISS_DIAG_IMG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISSESCALCAPACFUNCNAL.
FOR EACH cdgrhml.TISSESCALCAPACFUNCNAL NO-LOCK:
    CREATE ems5.TISSESCALCAPACFUNCNAL.
    BUFFER-COPY cdgrhml.TISSESCALCAPACFUNCNAL TO ems5.TISSESCALCAPACFUNCNAL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_ESTDIA.
FOR EACH cdgrhml.TISS_ESTDIA NO-LOCK:
    CREATE ems5.TISS_ESTDIA.
    BUFFER-COPY cdgrhml.TISS_ESTDIA TO ems5.TISS_ESTDIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_FACE_DENTE.
FOR EACH cdgrhml.TISS_FACE_DENTE NO-LOCK:
    CREATE ems5.TISS_FACE_DENTE.
    BUFFER-COPY cdgrhml.TISS_FACE_DENTE TO ems5.TISS_FACE_DENTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_FINALID_TRATAM.
FOR EACH cdgrhml.TISS_FINALID_TRATAM NO-LOCK:
    CREATE ems5.TISS_FINALID_TRATAM.
    BUFFER-COPY cdgrhml.TISS_FINALID_TRATAM TO ems5.TISS_FINALID_TRATAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_INDIC_ACID.
FOR EACH cdgrhml.TISS_INDIC_ACID NO-LOCK:
    CREATE ems5.TISS_INDIC_ACID.
    BUFFER-COPY cdgrhml.TISS_INDIC_ACID TO ems5.TISS_INDIC_ACID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_INSUMO.
FOR EACH cdgrhml.TISS_INSUMO NO-LOCK:
    CREATE ems5.TISS_INSUMO.
    BUFFER-COPY cdgrhml.TISS_INSUMO TO ems5.TISS_INSUMO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_REGIAO_BUCAL.
FOR EACH cdgrhml.TISS_REGIAO_BUCAL NO-LOCK:
    CREATE ems5.TISS_REGIAO_BUCAL.
    BUFFER-COPY cdgrhml.TISS_REGIAO_BUCAL TO ems5.TISS_REGIAO_BUCAL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_REGIM_INTRCAO.
FOR EACH cdgrhml.TISS_REGIM_INTRCAO NO-LOCK:
    CREATE ems5.TISS_REGIM_INTRCAO.
    BUFFER-COPY cdgrhml.TISS_REGIM_INTRCAO TO ems5.TISS_REGIM_INTRCAO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TEC_UTILIZA.
FOR EACH cdgrhml.TISS_TEC_UTILIZA NO-LOCK:
    CREATE ems5.TISS_TEC_UTILIZA.
    BUFFER-COPY cdgrhml.TISS_TEC_UTILIZA TO ems5.TISS_TEC_UTILIZA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_ACOMODA.
FOR EACH cdgrhml.TISS_TIP_ACOMODA NO-LOCK:
    CREATE ems5.TISS_TIP_ACOMODA.
    BUFFER-COPY cdgrhml.TISS_TIP_ACOMODA TO ems5.TISS_TIP_ACOMODA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_ATENDIM.
FOR EACH cdgrhml.TISS_TIP_ATENDIM NO-LOCK:
    CREATE ems5.TISS_TIP_ATENDIM.
    BUFFER-COPY cdgrhml.TISS_TIP_ATENDIM TO ems5.TISS_TIP_ATENDIM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISSTIPATENDIMODONTO.
FOR EACH cdgrhml.TISSTIPATENDIMODONTO NO-LOCK:
    CREATE ems5.TISSTIPATENDIMODONTO.
    BUFFER-COPY cdgrhml.TISSTIPATENDIMODONTO TO ems5.TISSTIPATENDIMODONTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_CON.
FOR EACH cdgrhml.TISS_TIP_CON NO-LOCK:
    CREATE ems5.TISS_TIP_CON.
    BUFFER-COPY cdgrhml.TISS_TIP_CON TO ems5.TISS_TIP_CON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_FATURAM.
FOR EACH cdgrhml.TISS_TIP_FATURAM NO-LOCK:
    CREATE ems5.TISS_TIP_FATURAM.
    BUFFER-COPY cdgrhml.TISS_TIP_FATURAM TO ems5.TISS_TIP_FATURAM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_INTRCAO.
FOR EACH cdgrhml.TISS_TIP_INTRCAO NO-LOCK:
    CREATE ems5.TISS_TIP_INTRCAO.
    BUFFER-COPY cdgrhml.TISS_TIP_INTRCAO TO ems5.TISS_TIP_INTRCAO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_QUI.
FOR EACH cdgrhml.TISS_TIP_QUI NO-LOCK:
    CREATE ems5.TISS_TIP_QUI.
    BUFFER-COPY cdgrhml.TISS_TIP_QUI TO ems5.TISS_TIP_QUI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_TIP_VIA.
FOR EACH cdgrhml.TISS_TIP_VIA NO-LOCK:
    CREATE ems5.TISS_TIP_VIA.
    BUFFER-COPY cdgrhml.TISS_TIP_VIA TO ems5.TISS_TIP_VIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TISS_VIA_ADMINIST.
FOR EACH cdgrhml.TISS_VIA_ADMINIST NO-LOCK:
    CREATE ems5.TISS_VIA_ADMINIST.
    BUFFER-COPY cdgrhml.TISS_VIA_ADMINIST TO ems5.TISS_VIA_ADMINIST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANCONV.
FOR EACH cdgrhml.TRANCONV NO-LOCK:
    CREATE ems5.TRANCONV.
    BUFFER-COPY cdgrhml.TRANCONV TO ems5.TRANCONV.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANPROC.
FOR EACH cdgrhml.TRANPROC NO-LOCK:
    CREATE ems5.TRANPROC.
    BUFFER-COPY cdgrhml.TRANPROC TO ems5.TRANPROC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANREVI.
FOR EACH cdgrhml.TRANREVI NO-LOCK:
    CREATE ems5.TRANREVI.
    BUFFER-COPY cdgrhml.TRANREVI TO ems5.TRANREVI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANS_AGRUP.
FOR EACH cdgrhml.TRANS_AGRUP NO-LOCK:
    CREATE ems5.TRANS_AGRUP.
    BUFFER-COPY cdgrhml.TRANS_AGRUP TO ems5.TRANS_AGRUP.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANSF_BNFCIAR_SELEC.
FOR EACH cdgrhml.TRANSF_BNFCIAR_SELEC NO-LOCK:
    CREATE ems5.TRANSF_BNFCIAR_SELEC.
    BUFFER-COPY cdgrhml.TRANSF_BNFCIAR_SELEC TO ems5.TRANSF_BNFCIAR_SELEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANSF_MODUL_OPCNAL.
FOR EACH cdgrhml.TRANSF_MODUL_OPCNAL NO-LOCK:
    CREATE ems5.TRANSF_MODUL_OPCNAL.
    BUFFER-COPY cdgrhml.TRANSF_MODUL_OPCNAL TO ems5.TRANSF_MODUL_OPCNAL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANTIPI.
FOR EACH cdgrhml.TRANTIPI NO-LOCK:
    CREATE ems5.TRANTIPI.
    BUFFER-COPY cdgrhml.TRANTIPI TO ems5.TRANTIPI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANUSUA.
FOR EACH cdgrhml.TRANUSUA NO-LOCK:
    CREATE ems5.TRANUSUA.
    BUFFER-COPY cdgrhml.TRANUSUA TO ems5.TRANUSUA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRATIPIN.
FOR EACH cdgrhml.TRATIPIN NO-LOCK:
    CREATE ems5.TRATIPIN.
    BUFFER-COPY cdgrhml.TRATIPIN TO ems5.TRATIPIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRMODAMB.
FOR EACH cdgrhml.TRMODAMB NO-LOCK:
    CREATE ems5.TRMODAMB.
    BUFFER-COPY cdgrhml.TRMODAMB TO ems5.TRMODAMB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRMODTPI.
FOR EACH cdgrhml.TRMODTPI NO-LOCK:
    CREATE ems5.TRMODTPI.
    BUFFER-COPY cdgrhml.TRMODTPI TO ems5.TRMODTPI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNIADMIN.
FOR EACH cdgrhml.UNIADMIN NO-LOCK:
    CREATE ems5.UNIADMIN.
    BUFFER-COPY cdgrhml.UNIADMIN TO ems5.UNIADMIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNICAMCO.
FOR EACH cdgrhml.UNICAMCO NO-LOCK:
    CREATE ems5.UNICAMCO.
    BUFFER-COPY cdgrhml.UNICAMCO TO ems5.UNICAMCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNI_TAXA.
FOR EACH cdgrhml.UNI_TAXA NO-LOCK:
    CREATE ems5.UNI_TAXA.
    BUFFER-COPY cdgrhml.UNI_TAXA TO ems5.UNI_TAXA.
END.


*/
