/*esse processo depende da criacao de um schema holder em separado,
para possibilitar acesso simultaneo a 2 ambientes.

DISABLE TRIGGERS FOR LOAD OF ems5.APROP_LANCTO_CTBL.
FOR EACH ems5hml.APROP_LANCTO_CTBL NO-LOCK:
    CREATE ems5.APROP_LANCTO_CTBL.
    BUFFER-COPY ems5hml.APROP_LANCTO_CTBL TO ems5.APROP_LANCTO_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BANCO.
FOR EACH ems5hml.BANCO NO-LOCK:
    CREATE ems5.BANCO.
    BUFFER-COPY ems5hml.BANCO TO ems5.BANCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BCO_TIP_CHEQ.
FOR EACH ems5hml.BCO_TIP_CHEQ NO-LOCK:
    CREATE ems5.BCO_TIP_CHEQ.
    BUFFER-COPY ems5hml.BCO_TIP_CHEQ TO ems5.BCO_TIP_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.BORD_ACR.
FOR EACH ems5hml.BORD_ACR NO-LOCK:
    CREATE ems5.BORD_ACR.
    BUFFER-COPY ems5hml.BORD_ACR TO ems5.BORD_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CALEND_COMIS.
FOR EACH ems5hml.CALEND_COMIS NO-LOCK:
    CREATE ems5.CALEND_COMIS.
    BUFFER-COPY ems5hml.CALEND_COMIS TO ems5.CALEND_COMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CALEND_GLOB.
FOR EACH ems5hml.CALEND_GLOB NO-LOCK:
    CREATE ems5.CALEND_GLOB.
    BUFFER-COPY ems5hml.CALEND_GLOB TO ems5.CALEND_GLOB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CART_BCIA.
FOR EACH ems5hml.CART_BCIA NO-LOCK:
    CREATE ems5.CART_BCIA.
    BUFFER-COPY ems5hml.CART_BCIA TO ems5.CART_BCIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CCUSTO.
FOR EACH ems5hml.CCUSTO NO-LOCK:
    CREATE ems5.CCUSTO.
    BUFFER-COPY ems5hml.CCUSTO TO ems5.CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CCUSTO_UNID_NEGOC.
FOR EACH ems5hml.CCUSTO_UNID_NEGOC NO-LOCK:
    CREATE ems5.CCUSTO_UNID_NEGOC.
    BUFFER-COPY ems5hml.CCUSTO_UNID_NEGOC TO ems5.CCUSTO_UNID_NEGOC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CENAR_CTBL.
FOR EACH ems5hml.CENAR_CTBL NO-LOCK:
    CREATE ems5.CENAR_CTBL.
    BUFFER-COPY ems5hml.CENAR_CTBL TO ems5.CENAR_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CHEQ_ACR.
FOR EACH ems5hml.CHEQ_ACR NO-LOCK:
    CREATE ems5.CHEQ_ACR.
    BUFFER-COPY ems5hml.CHEQ_ACR TO ems5.CHEQ_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLAS_DIA_CALEND.
FOR EACH ems5hml.CLAS_DIA_CALEND NO-LOCK:
    CREATE ems5.CLAS_DIA_CALEND.
    BUFFER-COPY ems5hml.CLAS_DIA_CALEND TO ems5.CLAS_DIA_CALEND.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASSIF_IMPTO.
FOR EACH ems5hml.CLASSIF_IMPTO NO-LOCK:
    CREATE ems5.CLASSIF_IMPTO.
    BUFFER-COPY ems5hml.CLASSIF_IMPTO TO ems5.CLASSIF_IMPTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CLASSIF_MSG_COBR.
FOR EACH ems5hml.CLASSIF_MSG_COBR NO-LOCK:
    CREATE ems5.CLASSIF_MSG_COBR.
    BUFFER-COPY ems5hml.CLASSIF_MSG_COBR TO ems5.CLASSIF_MSG_COBR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COL_FLUXO_CX.
FOR EACH ems5hml.COL_FLUXO_CX NO-LOCK:
    CREATE ems5.COL_FLUXO_CX.
    BUFFER-COPY ems5hml.COL_FLUXO_CX TO ems5.COL_FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COLPREFERDEMONSTCTBL.
FOR EACH ems5hml.COLPREFERDEMONSTCTBL NO-LOCK:
    CREATE ems5.COLPREFERDEMONSTCTBL.
    BUFFER-COPY ems5hml.COLPREFERDEMONSTCTBL TO ems5.COLPREFERDEMONSTCTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPL_COND_COBR_ACR.
FOR EACH ems5hml.COMPL_COND_COBR_ACR NO-LOCK:
    CREATE ems5.COMPL_COND_COBR_ACR.
    BUFFER-COPY ems5hml.COMPL_COND_COBR_ACR TO ems5.COMPL_COND_COBR_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPL_HISTOR_PADR.
FOR EACH ems5hml.COMPL_HISTOR_PADR NO-LOCK:
    CREATE ems5.COMPL_HISTOR_PADR.
    BUFFER-COPY ems5hml.COMPL_HISTOR_PADR TO ems5.COMPL_HISTOR_PADR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPL_MOVTO_PAGTO.
FOR EACH ems5hml.COMPL_MOVTO_PAGTO NO-LOCK:
    CREATE ems5.COMPL_MOVTO_PAGTO.
    BUFFER-COPY ems5hml.COMPL_MOVTO_PAGTO TO ems5.COMPL_MOVTO_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPL_MOVTO_TIT_ACR.
FOR EACH ems5hml.COMPL_MOVTO_TIT_ACR NO-LOCK:
    CREATE ems5.COMPL_MOVTO_TIT_ACR.
    BUFFER-COPY ems5hml.COMPL_MOVTO_TIT_ACR TO ems5.COMPL_MOVTO_TIT_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPL_PADR.
FOR EACH ems5hml.COMPL_PADR NO-LOCK:
    CREATE ems5.COMPL_PADR.
    BUFFER-COPY ems5hml.COMPL_PADR TO ems5.COMPL_PADR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPON_FORMUL_EDI.
FOR EACH ems5hml.COMPON_FORMUL_EDI NO-LOCK:
    CREATE ems5.COMPON_FORMUL_EDI.
    BUFFER-COPY ems5hml.COMPON_FORMUL_EDI TO ems5.COMPON_FORMUL_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPOS_DEMONST_CTBL.
FOR EACH ems5hml.COMPOS_DEMONST_CTBL NO-LOCK:
    CREATE ems5.COMPOS_DEMONST_CTBL.
    BUFFER-COPY ems5hml.COMPOS_DEMONST_CTBL TO ems5.COMPOS_DEMONST_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPOS_FINALID.
FOR EACH ems5hml.COMPOS_FINALID NO-LOCK:
    CREATE ems5.COMPOS_FINALID.
    BUFFER-COPY ems5hml.COMPOS_FINALID TO ems5.COMPOS_FINALID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPOS_FINALID_CMCMM.
FOR EACH ems5hml.COMPOS_FINALID_CMCMM NO-LOCK:
    CREATE ems5.COMPOS_FINALID_CMCMM.
    BUFFER-COPY ems5hml.COMPOS_FINALID_CMCMM TO ems5.COMPOS_FINALID_CMCMM.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPOS_PADR_FLUXO_CX.
FOR EACH ems5hml.COMPOS_PADR_FLUXO_CX NO-LOCK:
    CREATE ems5.COMPOS_PADR_FLUXO_CX.
    BUFFER-COPY ems5hml.COMPOS_PADR_FLUXO_CX TO ems5.COMPOS_PADR_FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COMPOS_UNID_CONTROL.
FOR EACH ems5hml.COMPOS_UNID_CONTROL NO-LOCK:
    CREATE ems5.COMPOS_UNID_CONTROL.
    BUFFER-COPY ems5hml.COMPOS_UNID_CONTROL TO ems5.COMPOS_UNID_CONTROL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COND_COBR_ACR.
FOR EACH ems5hml.COND_COBR_ACR NO-LOCK:
    CREATE ems5.COND_COBR_ACR.
    BUFFER-COPY ems5hml.COND_COBR_ACR TO ems5.COND_COBR_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONJTO_PREFER_DEMONST.
FOR EACH ems5hml.CONJTO_PREFER_DEMONST NO-LOCK:
    CREATE ems5.CONJTO_PREFER_DEMONST.
    BUFFER-COPY ems5hml.CONJTO_PREFER_DEMONST TO ems5.CONJTO_PREFER_DEMONST.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONTATO.
FOR EACH ems5hml.CONTATO NO-LOCK:
    CREATE ems5.CONTATO.
    BUFFER-COPY ems5hml.CONTATO TO ems5.CONTATO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CONTDO_REG_IMPORT_EDI.
FOR EACH ems5hml.CONTDO_REG_IMPORT_EDI NO-LOCK:
    CREATE ems5.CONTDO_REG_IMPORT_EDI.
    BUFFER-COPY ems5hml.CONTDO_REG_IMPORT_EDI TO ems5.CONTDO_REG_IMPORT_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.COTAC_PARID.
FOR EACH ems5hml.COTAC_PARID NO-LOCK:
    CREATE ems5.COTAC_PARID.
    BUFFER-COPY ems5hml.COTAC_PARID TO ems5.COTAC_PARID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CRITERDISTRIBCTACTBL.
FOR EACH ems5hml.CRITERDISTRIBCTACTBL NO-LOCK:
    CREATE ems5.CRITERDISTRIBCTACTBL.
    BUFFER-COPY ems5hml.CRITERDISTRIBCTACTBL TO ems5.CRITERDISTRIBCTACTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CORREN.
FOR EACH ems5hml.CTA_CORREN NO-LOCK:
    CREATE ems5.CTA_CORREN.
    BUFFER-COPY ems5hml.CTA_CORREN TO ems5.CTA_CORREN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CORREN_CTA_CTBL.
FOR EACH ems5hml.CTA_CORREN_CTA_CTBL NO-LOCK:
    CREATE ems5.CTA_CORREN_CTA_CTBL.
    BUFFER-COPY ems5hml.CTA_CORREN_CTA_CTBL TO ems5.CTA_CORREN_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CORREN_FORNEC.
FOR EACH ems5hml.CTA_CORREN_FORNEC NO-LOCK:
    CREATE ems5.CTA_CORREN_FORNEC.
    BUFFER-COPY ems5hml.CTA_CORREN_FORNEC TO ems5.CTA_CORREN_FORNEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CTBL.
FOR EACH ems5hml.CTA_CTBL NO-LOCK:
    CREATE ems5.CTA_CTBL.
    BUFFER-COPY ems5hml.CTA_CTBL TO ems5.CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CTBL_INTEGR.
FOR EACH ems5hml.CTA_CTBL_INTEGR NO-LOCK:
    CREATE ems5.CTA_CTBL_INTEGR.
    BUFFER-COPY ems5hml.CTA_CTBL_INTEGR TO ems5.CTA_CTBL_INTEGR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_CTBL_TIP_ABAT.
FOR EACH ems5hml.CTA_CTBL_TIP_ABAT NO-LOCK:
    CREATE ems5.CTA_CTBL_TIP_ABAT.
    BUFFER-COPY ems5hml.CTA_CTBL_TIP_ABAT TO ems5.CTA_CTBL_TIP_ABAT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_GRP_CLIEN.
FOR EACH ems5hml.CTA_GRP_CLIEN NO-LOCK:
    CREATE ems5.CTA_GRP_CLIEN.
    BUFFER-COPY ems5hml.CTA_GRP_CLIEN TO ems5.CTA_GRP_CLIEN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTAGRPCLIENPERDDEDUT.
FOR EACH ems5hml.CTAGRPCLIENPERDDEDUT NO-LOCK:
    CREATE ems5.CTAGRPCLIENPERDDEDUT.
    BUFFER-COPY ems5hml.CTAGRPCLIENPERDDEDUT TO ems5.CTAGRPCLIENPERDDEDUT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.CTA_GRP_FORNEC.
FOR EACH ems5hml.CTA_GRP_FORNEC NO-LOCK:
    CREATE ems5.CTA_GRP_FORNEC.
    BUFFER-COPY ems5hml.CTA_GRP_FORNEC TO ems5.CTA_GRP_FORNEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DEMONST_CTBL.
FOR EACH ems5hml.DEMONST_CTBL NO-LOCK:
    CREATE ems5.DEMONST_CTBL.
    BUFFER-COPY ems5hml.DEMONST_CTBL TO ems5.DEMONST_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.DIA_CALEND_GLOB.
FOR EACH ems5hml.DIA_CALEND_GLOB NO-LOCK:
    CREATE ems5.DIA_CALEND_GLOB.
    BUFFER-COPY ems5hml.DIA_CALEND_GLOB TO ems5.DIA_CALEND_GLOB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EMPRESA.
FOR EACH ems5hml.EMPRESA NO-LOCK:
    CREATE ems5.EMPRESA.
    BUFFER-COPY ems5hml.EMPRESA TO ems5.EMPRESA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESPEC_DOCTO.
FOR EACH ems5hml.ESPEC_DOCTO NO-LOCK:
    CREATE ems5.ESPEC_DOCTO.
    BUFFER-COPY ems5hml.ESPEC_DOCTO TO ems5.ESPEC_DOCTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESPEC_DOCTO_FINANC.
FOR EACH ems5hml.ESPEC_DOCTO_FINANC NO-LOCK:
    CREATE ems5.ESPEC_DOCTO_FINANC.
    BUFFER-COPY ems5hml.ESPEC_DOCTO_FINANC TO ems5.ESPEC_DOCTO_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESPEC_DOCTO_FINANC_ACR.
FOR EACH ems5hml.ESPEC_DOCTO_FINANC_ACR NO-LOCK:
    CREATE ems5.ESPEC_DOCTO_FINANC_ACR.
    BUFFER-COPY ems5hml.ESPEC_DOCTO_FINANC_ACR TO ems5.ESPEC_DOCTO_FINANC_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESPECREGRAPERDADEDUT.
FOR EACH ems5hml.ESPECREGRAPERDADEDUT NO-LOCK:
    CREATE ems5.ESPECREGRAPERDADEDUT.
    BUFFER-COPY ems5hml.ESPECREGRAPERDADEDUT TO ems5.ESPECREGRAPERDADEDUT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTABELECIMENTO.
FOR EACH ems5hml.ESTABELECIMENTO NO-LOCK:
    CREATE ems5.ESTABELECIMENTO.
    BUFFER-COPY ems5hml.ESTABELECIMENTO TO ems5.ESTABELECIMENTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTAB_UNID_NEGOC.
FOR EACH ems5hml.ESTAB_UNID_NEGOC NO-LOCK:
    CREATE ems5.ESTAB_UNID_NEGOC.
    BUFFER-COPY ems5hml.ESTAB_UNID_NEGOC TO ems5.ESTAB_UNID_NEGOC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_CCUSTO.
FOR EACH ems5hml.ESTRUT_CCUSTO NO-LOCK:
    CREATE ems5.ESTRUT_CCUSTO.
    BUFFER-COPY ems5hml.ESTRUT_CCUSTO TO ems5.ESTRUT_CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_CTA_CTBL.
FOR EACH ems5hml.ESTRUT_CTA_CTBL NO-LOCK:
    CREATE ems5.ESTRUT_CTA_CTBL.
    BUFFER-COPY ems5hml.ESTRUT_CTA_CTBL TO ems5.ESTRUT_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUTCTBLMOVTOANALIT.
FOR EACH ems5hml.ESTRUTCTBLMOVTOANALIT NO-LOCK:
    CREATE ems5.ESTRUTCTBLMOVTOANALIT.
    BUFFER-COPY ems5hml.ESTRUTCTBLMOVTOANALIT TO ems5.ESTRUTCTBLMOVTOANALIT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_CTBL_MOVTO_SINT.
FOR EACH ems5hml.ESTRUT_CTBL_MOVTO_SINT NO-LOCK:
    CREATE ems5.ESTRUT_CTBL_MOVTO_SINT.
    BUFFER-COPY ems5hml.ESTRUT_CTBL_MOVTO_SINT TO ems5.ESTRUT_CTBL_MOVTO_SINT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_REPRES.
FOR EACH ems5hml.ESTRUT_REPRES NO-LOCK:
    CREATE ems5.ESTRUT_REPRES.
    BUFFER-COPY ems5hml.ESTRUT_REPRES TO ems5.ESTRUT_REPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUTTIPFLUXOFINANC.
FOR EACH ems5hml.ESTRUTTIPFLUXOFINANC NO-LOCK:
    CREATE ems5.ESTRUTTIPFLUXOFINANC.
    BUFFER-COPY ems5hml.ESTRUTTIPFLUXOFINANC TO ems5.ESTRUTTIPFLUXOFINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_UNID_CONTROL.
FOR EACH ems5hml.ESTRUT_UNID_CONTROL NO-LOCK:
    CREATE ems5.ESTRUT_UNID_CONTROL.
    BUFFER-COPY ems5hml.ESTRUT_UNID_CONTROL TO ems5.ESTRUT_UNID_CONTROL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_UNID_NEGOC.
FOR EACH ems5hml.ESTRUT_UNID_NEGOC NO-LOCK:
    CREATE ems5.ESTRUT_UNID_NEGOC.
    BUFFER-COPY ems5hml.ESTRUT_UNID_NEGOC TO ems5.ESTRUT_UNID_NEGOC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_UNID_ORGAN.
FOR EACH ems5hml.ESTRUT_UNID_ORGAN NO-LOCK:
    CREATE ems5.ESTRUT_UNID_ORGAN.
    BUFFER-COPY ems5hml.ESTRUT_UNID_ORGAN TO ems5.ESTRUT_UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ESTRUT_VISUALIZ_CTBL.
FOR EACH ems5hml.ESTRUT_VISUALIZ_CTBL NO-LOCK:
    CREATE ems5.ESTRUT_VISUALIZ_CTBL.
    BUFFER-COPY ems5hml.ESTRUT_VISUALIZ_CTBL TO ems5.ESTRUT_VISUALIZ_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.EXERC_CTBL.
FOR EACH ems5hml.EXERC_CTBL NO-LOCK:
    CREATE ems5.EXERC_CTBL.
    BUFFER-COPY ems5hml.EXERC_CTBL TO ems5.EXERC_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FER_NAC.
FOR EACH ems5hml.FER_NAC NO-LOCK:
    CREATE ems5.FER_NAC.
    BUFFER-COPY ems5hml.FER_NAC TO ems5.FER_NAC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FINALID_ECON.
FOR EACH ems5hml.FINALID_ECON NO-LOCK:
    CREATE ems5.FINALID_ECON.
    BUFFER-COPY ems5hml.FINALID_ECON TO ems5.FINALID_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FINALID_UNID_ORGAN.
FOR EACH ems5hml.FINALID_UNID_ORGAN NO-LOCK:
    CREATE ems5.FINALID_UNID_ORGAN.
    BUFFER-COPY ems5hml.FINALID_UNID_ORGAN TO ems5.FINALID_UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FINALID_UTILIZ_CENAR.
FOR EACH ems5hml.FINALID_UTILIZ_CENAR NO-LOCK:
    CREATE ems5.FINALID_UTILIZ_CENAR.
    BUFFER-COPY ems5hml.FINALID_UTILIZ_CENAR TO ems5.FINALID_UTILIZ_CENAR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FLUXO_CX.
FOR EACH ems5hml.FLUXO_CX NO-LOCK:
    CREATE ems5.FLUXO_CX.
    BUFFER-COPY ems5hml.FLUXO_CX TO ems5.FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMA_PAGTO.
FOR EACH ems5hml.FORMA_PAGTO NO-LOCK:
    CREATE ems5.FORMA_PAGTO.
    BUFFER-COPY ems5hml.FORMA_PAGTO TO ems5.FORMA_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMA_PAGTO_BCO.
FOR EACH ems5hml.FORMA_PAGTO_BCO NO-LOCK:
    CREATE ems5.FORMA_PAGTO_BCO.
    BUFFER-COPY ems5hml.FORMA_PAGTO_BCO TO ems5.FORMA_PAGTO_BCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMAT_DAT_GERAL_EDI.
FOR EACH ems5hml.FORMAT_DAT_GERAL_EDI NO-LOCK:
    CREATE ems5.FORMAT_DAT_GERAL_EDI.
    BUFFER-COPY ems5hml.FORMAT_DAT_GERAL_EDI TO ems5.FORMAT_DAT_GERAL_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMAT_DEC_GERAL_EDI.
FOR EACH ems5hml.FORMAT_DEC_GERAL_EDI NO-LOCK:
    CREATE ems5.FORMAT_DEC_GERAL_EDI.
    BUFFER-COPY ems5hml.FORMAT_DEC_GERAL_EDI TO ems5.FORMAT_DEC_GERAL_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.FORMUL_EDI.
FOR EACH ems5hml.FORMUL_EDI NO-LOCK:
    CREATE ems5.FORMUL_EDI.
    BUFFER-COPY ems5hml.FORMUL_EDI TO ems5.FORMUL_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_CLIEN.
FOR EACH ems5hml.GRP_CLIEN NO-LOCK:
    CREATE ems5.GRP_CLIEN.
    BUFFER-COPY ems5hml.GRP_CLIEN TO ems5.GRP_CLIEN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_CTA_CTBL.
FOR EACH ems5hml.GRP_CTA_CTBL NO-LOCK:
    CREATE ems5.GRP_CTA_CTBL.
    BUFFER-COPY ems5hml.GRP_CTA_CTBL TO ems5.GRP_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_FORNEC.
FOR EACH ems5hml.GRP_FORNEC NO-LOCK:
    CREATE ems5.GRP_FORNEC.
    BUFFER-COPY ems5hml.GRP_FORNEC TO ems5.GRP_FORNEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.GRP_REPRES.
FOR EACH ems5hml.GRP_REPRES NO-LOCK:
    CREATE ems5.GRP_REPRES.
    BUFFER-COPY ems5hml.GRP_REPRES TO ems5.GRP_REPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_FINALID_ECON.
FOR EACH ems5hml.HISTOR_FINALID_ECON NO-LOCK:
    CREATE ems5.HISTOR_FINALID_ECON.
    BUFFER-COPY ems5hml.HISTOR_FINALID_ECON TO ems5.HISTOR_FINALID_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_GENER.
FOR EACH ems5hml.HISTOR_GENER NO-LOCK:
    CREATE ems5.HISTOR_GENER.
    BUFFER-COPY ems5hml.HISTOR_GENER TO ems5.HISTOR_GENER.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_IMPTO_EMPRES.
FOR EACH ems5hml.HISTOR_IMPTO_EMPRES NO-LOCK:
    CREATE ems5.HISTOR_IMPTO_EMPRES.
    BUFFER-COPY ems5hml.HISTOR_IMPTO_EMPRES TO ems5.HISTOR_IMPTO_EMPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_PADR.
FOR EACH ems5hml.HISTOR_PADR NO-LOCK:
    CREATE ems5.HISTOR_PADR.
    BUFFER-COPY ems5hml.HISTOR_PADR TO ems5.HISTOR_PADR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTOR_PARAM_CTBZ.
FOR EACH ems5hml.HISTOR_PARAM_CTBZ NO-LOCK:
    CREATE ems5.HISTOR_PARAM_CTBZ.
    BUFFER-COPY ems5hml.HISTOR_PARAM_CTBZ TO ems5.HISTOR_PARAM_CTBZ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.HISTORPARAMINTEGREMS.
FOR EACH ems5hml.HISTORPARAMINTEGREMS NO-LOCK:
    CREATE ems5.HISTORPARAMINTEGREMS.
    BUFFER-COPY ems5hml.HISTORPARAMINTEGREMS TO ems5.HISTORPARAMINTEGREMS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.IDIOM_CONTAT.
FOR EACH ems5hml.IDIOM_CONTAT NO-LOCK:
    CREATE ems5.IDIOM_CONTAT.
    BUFFER-COPY ems5hml.IDIOM_CONTAT TO ems5.IDIOM_CONTAT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.IDIOM_PAIS.
FOR EACH ems5hml.IDIOM_PAIS NO-LOCK:
    CREATE ems5.IDIOM_PAIS.
    BUFFER-COPY ems5hml.IDIOM_PAIS TO ems5.IDIOM_PAIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.IMPOSTO.
FOR EACH ems5hml.IMPOSTO NO-LOCK:
    CREATE ems5.IMPOSTO.
    BUFFER-COPY ems5hml.IMPOSTO TO ems5.IMPOSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.IMPTO_VINCUL_EMPRES.
FOR EACH ems5hml.IMPTO_VINCUL_EMPRES NO-LOCK:
    CREATE ems5.IMPTO_VINCUL_EMPRES.
    BUFFER-COPY ems5hml.IMPTO_VINCUL_EMPRES TO ems5.IMPTO_VINCUL_EMPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INDIC_ECON.
FOR EACH ems5hml.INDIC_ECON NO-LOCK:
    CREATE ems5.INDIC_ECON.
    BUFFER-COPY ems5hml.INDIC_ECON TO ems5.INDIC_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INSTRUC_BCIA.
FOR EACH ems5hml.INSTRUC_BCIA NO-LOCK:
    CREATE ems5.INSTRUC_BCIA.
    BUFFER-COPY ems5hml.INSTRUC_BCIA TO ems5.INSTRUC_BCIA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.INSTRUC_BCIA_BCO.
FOR EACH ems5hml.INSTRUC_BCIA_BCO NO-LOCK:
    CREATE ems5.INSTRUC_BCIA_BCO.
    BUFFER-COPY ems5hml.INSTRUC_BCIA_BCO TO ems5.INSTRUC_BCIA_BCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_LANCTO_CTBL.
FOR EACH ems5hml.ITEM_LANCTO_CTBL NO-LOCK:
    CREATE ems5.ITEM_LANCTO_CTBL.
    BUFFER-COPY ems5hml.ITEM_LANCTO_CTBL TO ems5.ITEM_LANCTO_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_LANCTO_CTBL_PADR.
FOR EACH ems5hml.ITEM_LANCTO_CTBL_PADR NO-LOCK:
    CREATE ems5.ITEM_LANCTO_CTBL_PADR.
    BUFFER-COPY ems5hml.ITEM_LANCTO_CTBL_PADR TO ems5.ITEM_LANCTO_CTBL_PADR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_LISTA_CCUSTO.
FOR EACH ems5hml.ITEM_LISTA_CCUSTO NO-LOCK:
    CREATE ems5.ITEM_LISTA_CCUSTO.
    BUFFER-COPY ems5hml.ITEM_LISTA_CCUSTO TO ems5.ITEM_LISTA_CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_LOTE_PAGTO.
FOR EACH ems5hml.ITEM_LOTE_PAGTO NO-LOCK:
    CREATE ems5.ITEM_LOTE_PAGTO.
    BUFFER-COPY ems5hml.ITEM_LOTE_PAGTO TO ems5.ITEM_LOTE_PAGTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_RAT_CTBL.
FOR EACH ems5hml.ITEM_RAT_CTBL NO-LOCK:
    CREATE ems5.ITEM_RAT_CTBL.
    BUFFER-COPY ems5hml.ITEM_RAT_CTBL TO ems5.ITEM_RAT_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_RENEGOC_ACR.
FOR EACH ems5hml.ITEM_RENEGOC_ACR NO-LOCK:
    CREATE ems5.ITEM_RENEGOC_ACR.
    BUFFER-COPY ems5hml.ITEM_RENEGOC_ACR TO ems5.ITEM_RENEGOC_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.ITEM_TAB_PRGSSIV_IMPTO.
FOR EACH ems5hml.ITEM_TAB_PRGSSIV_IMPTO NO-LOCK:
    CREATE ems5.ITEM_TAB_PRGSSIV_IMPTO.
    BUFFER-COPY ems5hml.ITEM_TAB_PRGSSIV_IMPTO TO ems5.ITEM_TAB_PRGSSIV_IMPTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LAYOUT_CHEQ.
FOR EACH ems5hml.LAYOUT_CHEQ NO-LOCK:
    CREATE ems5.LAYOUT_CHEQ.
    BUFFER-COPY ems5hml.LAYOUT_CHEQ TO ems5.LAYOUT_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LAYOUT_COL_FLUXO_CX.
FOR EACH ems5hml.LAYOUT_COL_FLUXO_CX NO-LOCK:
    CREATE ems5.LAYOUT_COL_FLUXO_CX.
    BUFFER-COPY ems5hml.LAYOUT_COL_FLUXO_CX TO ems5.LAYOUT_COL_FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LAYOUT_CTA_CTBL.
FOR EACH ems5hml.LAYOUT_CTA_CTBL NO-LOCK:
    CREATE ems5.LAYOUT_CTA_CTBL.
    BUFFER-COPY ems5hml.LAYOUT_CTA_CTBL TO ems5.LAYOUT_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LAYOUT_INTEGR_CTBL_EXT.
FOR EACH ems5hml.LAYOUT_INTEGR_CTBL_EXT NO-LOCK:
    CREATE ems5.LAYOUT_INTEGR_CTBL_EXT.
    BUFFER-COPY ems5hml.LAYOUT_INTEGR_CTBL_EXT TO ems5.LAYOUT_INTEGR_CTBL_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LIN_LAYOUT_CHEQ.
FOR EACH ems5hml.LIN_LAYOUT_CHEQ NO-LOCK:
    CREATE ems5.LIN_LAYOUT_CHEQ.
    BUFFER-COPY ems5hml.LIN_LAYOUT_CHEQ TO ems5.LIN_LAYOUT_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LIN_LAYOUT_CTA_CTBL.
FOR EACH ems5hml.LIN_LAYOUT_CTA_CTBL NO-LOCK:
    CREATE ems5.LIN_LAYOUT_CTA_CTBL.
    BUFFER-COPY ems5hml.LIN_LAYOUT_CTA_CTBL TO ems5.LIN_LAYOUT_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LIVRO_FISC.
FOR EACH ems5hml.LIVRO_FISC NO-LOCK:
    CREATE ems5.LIVRO_FISC.
    BUFFER-COPY ems5hml.LIVRO_FISC TO ems5.LIVRO_FISC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.LOCALIZ_ARQ_EDI.
FOR EACH ems5hml.LOCALIZ_ARQ_EDI NO-LOCK:
    CREATE ems5.LOCALIZ_ARQ_EDI.
    BUFFER-COPY ems5hml.LOCALIZ_ARQ_EDI TO ems5.LOCALIZ_ARQ_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZTRADCTACTBLEXT.
FOR EACH ems5hml.MATRIZTRADCTACTBLEXT NO-LOCK:
    CREATE ems5.MATRIZTRADCTACTBLEXT.
    BUFFER-COPY ems5hml.MATRIZTRADCTACTBLEXT TO ems5.MATRIZTRADCTACTBLEXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZTRADFINALIDEXT.
FOR EACH ems5hml.MATRIZTRADFINALIDEXT NO-LOCK:
    CREATE ems5.MATRIZTRADFINALIDEXT.
    BUFFER-COPY ems5hml.MATRIZTRADFINALIDEXT TO ems5.MATRIZTRADFINALIDEXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZ_TRAD_FLUXO_EXT.
FOR EACH ems5hml.MATRIZ_TRAD_FLUXO_EXT NO-LOCK:
    CREATE ems5.MATRIZ_TRAD_FLUXO_EXT.
    BUFFER-COPY ems5hml.MATRIZ_TRAD_FLUXO_EXT TO ems5.MATRIZ_TRAD_FLUXO_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZ_TRAD_ORG_EXT.
FOR EACH ems5hml.MATRIZ_TRAD_ORG_EXT NO-LOCK:
    CREATE ems5.MATRIZ_TRAD_ORG_EXT.
    BUFFER-COPY ems5hml.MATRIZ_TRAD_ORG_EXT TO ems5.MATRIZ_TRAD_ORG_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZ_TRAD_PAIS_EXT.
FOR EACH ems5hml.MATRIZ_TRAD_PAIS_EXT NO-LOCK:
    CREATE ems5.MATRIZ_TRAD_PAIS_EXT.
    BUFFER-COPY ems5hml.MATRIZ_TRAD_PAIS_EXT TO ems5.MATRIZ_TRAD_PAIS_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MATRIZ_TRAD_PORTAD_EXT.
FOR EACH ems5hml.MATRIZ_TRAD_PORTAD_EXT NO-LOCK:
    CREATE ems5.MATRIZ_TRAD_PORTAD_EXT.
    BUFFER-COPY ems5hml.MATRIZ_TRAD_PORTAD_EXT TO ems5.MATRIZ_TRAD_PORTAD_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTIV_DEVOL_CHEQ.
FOR EACH ems5hml.MOTIV_DEVOL_CHEQ NO-LOCK:
    CREATE ems5.MOTIV_DEVOL_CHEQ.
    BUFFER-COPY ems5hml.MOTIV_DEVOL_CHEQ TO ems5.MOTIV_DEVOL_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOTIV_MOVTO_TIT_ACR.
FOR EACH ems5hml.MOTIV_MOVTO_TIT_ACR NO-LOCK:
    CREATE ems5.MOTIV_MOVTO_TIT_ACR.
    BUFFER-COPY ems5hml.MOTIV_MOVTO_TIT_ACR TO ems5.MOTIV_MOVTO_TIT_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVTO_CTA_CORREN.
FOR EACH ems5hml.MOVTO_CTA_CORREN NO-LOCK:
    CREATE ems5.MOVTO_CTA_CORREN.
    BUFFER-COPY ems5hml.MOVTO_CTA_CORREN TO ems5.MOVTO_CTA_CORREN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.MOVTO_DEVOL_CHEQ_ACR.
FOR EACH ems5hml.MOVTO_DEVOL_CHEQ_ACR NO-LOCK:
    CREATE ems5.MOVTO_DEVOL_CHEQ_ACR.
    BUFFER-COPY ems5hml.MOVTO_DEVOL_CHEQ_ACR TO ems5.MOVTO_DEVOL_CHEQ_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.OCOR_BCIA_BCO.
FOR EACH ems5hml.OCOR_BCIA_BCO NO-LOCK:
    CREATE ems5.OCOR_BCIA_BCO.
    BUFFER-COPY ems5hml.OCOR_BCIA_BCO TO ems5.OCOR_BCIA_BCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.OCOR_PROCES_EDI.
FOR EACH ems5hml.OCOR_PROCES_EDI NO-LOCK:
    CREATE ems5.OCOR_PROCES_EDI.
    BUFFER-COPY ems5hml.OCOR_PROCES_EDI TO ems5.OCOR_PROCES_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PADR_FLUXO_CX.
FOR EACH ems5hml.PADR_FLUXO_CX NO-LOCK:
    CREATE ems5.PADR_FLUXO_CX.
    BUFFER-COPY ems5hml.PADR_FLUXO_CX TO ems5.PADR_FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PAG_LIVRO_FISC.
FOR EACH ems5hml.PAG_LIVRO_FISC NO-LOCK:
    CREATE ems5.PAG_LIVRO_FISC.
    BUFFER-COPY ems5hml.PAG_LIVRO_FISC TO ems5.PAG_LIVRO_FISC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PAGTO_PADR.
FOR EACH ems5hml.PAGTO_PADR NO-LOCK:
    CREATE ems5.PAGTO_PADR.
    BUFFER-COPY ems5hml.PAGTO_PADR TO ems5.PAGTO_PADR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PAGTO_PROVIS_REPET.
FOR EACH ems5hml.PAGTO_PROVIS_REPET NO-LOCK:
    CREATE ems5.PAGTO_PROVIS_REPET.
    BUFFER-COPY ems5hml.PAGTO_PROVIS_REPET TO ems5.PAGTO_PROVIS_REPET.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PAIS.
FOR EACH ems5hml.PAIS NO-LOCK:
    CREATE ems5.PAIS.
    BUFFER-COPY ems5hml.PAIS TO ems5.PAIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_CTBZ.
FOR EACH ems5hml.PARAM_CTBZ NO-LOCK:
    CREATE ems5.PARAM_CTBZ.
    BUFFER-COPY ems5hml.PARAM_CTBZ TO ems5.PARAM_CTBZ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_CTBZ_COMIS.
FOR EACH ems5hml.PARAM_CTBZ_COMIS NO-LOCK:
    CREATE ems5.PARAM_CTBZ_COMIS.
    BUFFER-COPY ems5hml.PARAM_CTBZ_COMIS TO ems5.PARAM_CTBZ_COMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_EMPRES_ACR.
FOR EACH ems5hml.PARAM_EMPRES_ACR NO-LOCK:
    CREATE ems5.PARAM_EMPRES_ACR.
    BUFFER-COPY ems5hml.PARAM_EMPRES_ACR TO ems5.PARAM_EMPRES_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_EMPRES_APB.
FOR EACH ems5hml.PARAM_EMPRES_APB NO-LOCK:
    CREATE ems5.PARAM_EMPRES_APB.
    BUFFER-COPY ems5hml.PARAM_EMPRES_APB TO ems5.PARAM_EMPRES_APB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_ESTAB_ACR.
FOR EACH ems5hml.PARAM_ESTAB_ACR NO-LOCK:
    CREATE ems5.PARAM_ESTAB_ACR.
    BUFFER-COPY ems5hml.PARAM_ESTAB_ACR TO ems5.PARAM_ESTAB_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_ESTAB_APB.
FOR EACH ems5hml.PARAM_ESTAB_APB NO-LOCK:
    CREATE ems5.PARAM_ESTAB_APB.
    BUFFER-COPY ems5hml.PARAM_ESTAB_APB TO ems5.PARAM_ESTAB_APB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_ESTAB_CMG.
FOR EACH ems5hml.PARAM_ESTAB_CMG NO-LOCK:
    CREATE ems5.PARAM_ESTAB_CMG.
    BUFFER-COPY ems5hml.PARAM_ESTAB_CMG TO ems5.PARAM_ESTAB_CMG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_ESTAB_COMIS.
FOR EACH ems5hml.PARAM_ESTAB_COMIS NO-LOCK:
    CREATE ems5.PARAM_ESTAB_COMIS.
    BUFFER-COPY ems5hml.PARAM_ESTAB_COMIS TO ems5.PARAM_ESTAB_COMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_ACR.
FOR EACH ems5hml.PARAM_GERAL_ACR NO-LOCK:
    CREATE ems5.PARAM_GERAL_ACR.
    BUFFER-COPY ems5hml.PARAM_GERAL_ACR TO ems5.PARAM_GERAL_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_APB.
FOR EACH ems5hml.PARAM_GERAL_APB NO-LOCK:
    CREATE ems5.PARAM_GERAL_APB.
    BUFFER-COPY ems5hml.PARAM_GERAL_APB TO ems5.PARAM_GERAL_APB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_CFL.
FOR EACH ems5hml.PARAM_GERAL_CFL NO-LOCK:
    CREATE ems5.PARAM_GERAL_CFL.
    BUFFER-COPY ems5hml.PARAM_GERAL_CFL TO ems5.PARAM_GERAL_CFL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_CMG.
FOR EACH ems5hml.PARAM_GERAL_CMG NO-LOCK:
    CREATE ems5.PARAM_GERAL_CMG.
    BUFFER-COPY ems5hml.PARAM_GERAL_CMG TO ems5.PARAM_GERAL_CMG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_EMS.
FOR EACH ems5hml.PARAM_GERAL_EMS NO-LOCK:
    CREATE ems5.PARAM_GERAL_EMS.
    BUFFER-COPY ems5hml.PARAM_GERAL_EMS TO ems5.PARAM_GERAL_EMS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_GERAL_GLD.
FOR EACH ems5hml.PARAM_GERAL_GLD NO-LOCK:
    CREATE ems5.PARAM_GERAL_GLD.
    BUFFER-COPY ems5hml.PARAM_GERAL_GLD TO ems5.PARAM_GERAL_GLD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_INTEGR_CFL.
FOR EACH ems5hml.PARAM_INTEGR_CFL NO-LOCK:
    CREATE ems5.PARAM_INTEGR_CFL.
    BUFFER-COPY ems5hml.PARAM_INTEGR_CFL TO ems5.PARAM_INTEGR_CFL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_INTEGR_EMS.
FOR EACH ems5hml.PARAM_INTEGR_EMS NO-LOCK:
    CREATE ems5.PARAM_INTEGR_EMS.
    BUFFER-COPY ems5hml.PARAM_INTEGR_EMS TO ems5.PARAM_INTEGR_EMS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAMREGRAPERDADEDUT.
FOR EACH ems5hml.PARAMREGRAPERDADEDUT NO-LOCK:
    CREATE ems5.PARAMREGRAPERDADEDUT.
    BUFFER-COPY ems5hml.PARAMREGRAPERDADEDUT TO ems5.PARAMREGRAPERDADEDUT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARAM_UTILIZ_PRODUT.
FOR EACH ems5hml.PARAM_UTILIZ_PRODUT NO-LOCK:
    CREATE ems5.PARAM_UTILIZ_PRODUT.
    BUFFER-COPY ems5hml.PARAM_UTILIZ_PRODUT TO ems5.PARAM_UTILIZ_PRODUT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARCEI_EDI.
FOR EACH ems5hml.PARCEI_EDI NO-LOCK:
    CREATE ems5.PARCEI_EDI.
    BUFFER-COPY ems5hml.PARCEI_EDI TO ems5.PARCEI_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARCEI_MAPA_EDI.
FOR EACH ems5hml.PARCEI_MAPA_EDI NO-LOCK:
    CREATE ems5.PARCEI_MAPA_EDI.
    BUFFER-COPY ems5hml.PARCEI_MAPA_EDI TO ems5.PARCEI_MAPA_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARCEI_TRANS_EDI.
FOR EACH ems5hml.PARCEI_TRANS_EDI NO-LOCK:
    CREATE ems5.PARCEI_TRANS_EDI.
    BUFFER-COPY ems5hml.PARCEI_TRANS_EDI TO ems5.PARCEI_TRANS_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PARID_INDIC_ECON.
FOR EACH ems5hml.PARID_INDIC_ECON NO-LOCK:
    CREATE ems5.PARID_INDIC_ECON.
    BUFFER-COPY ems5hml.PARID_INDIC_ECON TO ems5.PARID_INDIC_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PERIOD_CTBL.
FOR EACH ems5hml.PERIOD_CTBL NO-LOCK:
    CREATE ems5.PERIOD_CTBL.
    BUFFER-COPY ems5hml.PERIOD_CTBL TO ems5.PERIOD_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PLANO_CCUSTO.
FOR EACH ems5hml.PLANO_CCUSTO NO-LOCK:
    CREATE ems5.PLANO_CCUSTO.
    BUFFER-COPY ems5hml.PLANO_CCUSTO TO ems5.PLANO_CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PLANO_CTA_CTBL.
FOR EACH ems5hml.PLANO_CTA_CTBL NO-LOCK:
    CREATE ems5.PLANO_CTA_CTBL.
    BUFFER-COPY ems5hml.PLANO_CTA_CTBL TO ems5.PLANO_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PLANO_CTA_UNID_ORGAN.
FOR EACH ems5hml.PLANO_CTA_UNID_ORGAN NO-LOCK:
    CREATE ems5.PLANO_CTA_UNID_ORGAN.
    BUFFER-COPY ems5hml.PLANO_CTA_UNID_ORGAN TO ems5.PLANO_CTA_UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTAD_BCO.
FOR EACH ems5hml.PORTAD_BCO NO-LOCK:
    CREATE ems5.PORTAD_BCO.
    BUFFER-COPY ems5hml.PORTAD_BCO TO ems5.PORTAD_BCO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTAD_EDI.
FOR EACH ems5hml.PORTAD_EDI NO-LOCK:
    CREATE ems5.PORTAD_EDI.
    BUFFER-COPY ems5hml.PORTAD_EDI TO ems5.PORTAD_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTAD_ESTAB.
FOR EACH ems5hml.PORTAD_ESTAB NO-LOCK:
    CREATE ems5.PORTAD_ESTAB.
    BUFFER-COPY ems5hml.PORTAD_ESTAB TO ems5.PORTAD_ESTAB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTAD_FINALID_ECON.
FOR EACH ems5hml.PORTAD_FINALID_ECON NO-LOCK:
    CREATE ems5.PORTAD_FINALID_ECON.
    BUFFER-COPY ems5hml.PORTAD_FINALID_ECON TO ems5.PORTAD_FINALID_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PORTADOR.
FOR EACH ems5hml.PORTADOR NO-LOCK:
    CREATE ems5.PORTADOR.
    BUFFER-COPY ems5hml.PORTADOR TO ems5.PORTADOR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.POS_COD_BARRA.
FOR EACH ems5hml.POS_COD_BARRA NO-LOCK:
    CREATE ems5.POS_COD_BARRA.
    BUFFER-COPY ems5hml.POS_COD_BARRA TO ems5.POS_COD_BARRA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PREFER_DEMONST_CTBL.
FOR EACH ems5hml.PREFER_DEMONST_CTBL NO-LOCK:
    CREATE ems5.PREFER_DEMONST_CTBL.
    BUFFER-COPY ems5hml.PREFER_DEMONST_CTBL TO ems5.PREFER_DEMONST_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PREFER_USUAR_CFL.
FOR EACH ems5hml.PREFER_USUAR_CFL NO-LOCK:
    CREATE ems5.PREFER_USUAR_CFL.
    BUFFER-COPY ems5hml.PREFER_USUAR_CFL TO ems5.PREFER_USUAR_CFL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PREFER_USUAR_CMG.
FOR EACH ems5hml.PREFER_USUAR_CMG NO-LOCK:
    CREATE ems5.PREFER_USUAR_CMG.
    BUFFER-COPY ems5hml.PREFER_USUAR_CMG TO ems5.PREFER_USUAR_CMG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PROJ_FINANC.
FOR EACH ems5hml.PROJ_FINANC NO-LOCK:
    CREATE ems5.PROJ_FINANC.
    BUFFER-COPY ems5hml.PROJ_FINANC TO ems5.PROJ_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.PROJ_FINANC_ESTAB.
FOR EACH ems5hml.PROJ_FINANC_ESTAB NO-LOCK:
    CREATE ems5.PROJ_FINANC_ESTAB.
    BUFFER-COPY ems5hml.PROJ_FINANC_ESTAB TO ems5.PROJ_FINANC_ESTAB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RATMOTIVMOVTOTITACR.
FOR EACH ems5hml.RATMOTIVMOVTOTITACR NO-LOCK:
    CREATE ems5.RATMOTIVMOVTOTITACR.
    BUFFER-COPY ems5hml.RATMOTIVMOVTOTITACR TO ems5.RATMOTIVMOVTOTITACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REGRA_PERDA_DEDUT.
FOR EACH ems5hml.REGRA_PERDA_DEDUT NO-LOCK:
    CREATE ems5.REGRA_PERDA_DEDUT.
    BUFFER-COPY ems5hml.REGRA_PERDA_DEDUT TO ems5.REGRA_PERDA_DEDUT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RELACTO_CHEQ_ACR.
FOR EACH ems5hml.RELACTO_CHEQ_ACR NO-LOCK:
    CREATE ems5.RELACTO_CHEQ_ACR.
    BUFFER-COPY ems5hml.RELACTO_CHEQ_ACR TO ems5.RELACTO_CHEQ_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RELACTO_TIT_ACR.
FOR EACH ems5hml.RELACTO_TIT_ACR NO-LOCK:
    CREATE ems5.RELACTO_TIT_ACR.
    BUFFER-COPY ems5hml.RELACTO_TIT_ACR TO ems5.RELACTO_TIT_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.RENEGOC_ACR.
FOR EACH ems5hml.RENEGOC_ACR NO-LOCK:
    CREATE ems5.RENEGOC_ACR.
    BUFFER-COPY ems5hml.RENEGOC_ACR TO ems5.RENEGOC_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REPRESENTANTE.
FOR EACH ems5hml.REPRESENTANTE NO-LOCK:
    CREATE ems5.REPRESENTANTE.
    BUFFER-COPY ems5hml.REPRESENTANTE TO ems5.REPRESENTANTE.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.REPRES_FINANC.
FOR EACH ems5hml.REPRES_FINANC NO-LOCK:
    CREATE ems5.REPRES_FINANC.
    BUFFER-COPY ems5hml.REPRES_FINANC TO ems5.REPRES_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SDO_CTA_CTBL_MODUL.
FOR EACH ems5hml.SDO_CTA_CTBL_MODUL NO-LOCK:
    CREATE ems5.SDO_CTA_CTBL_MODUL.
    BUFFER-COPY ems5hml.SDO_CTA_CTBL_MODUL TO ems5.SDO_CTA_CTBL_MODUL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_AJUST_SIT_PERIOD.
FOR EACH ems5hml.SEGUR_AJUST_SIT_PERIOD NO-LOCK:
    CREATE ems5.SEGUR_AJUST_SIT_PERIOD.
    BUFFER-COPY ems5hml.SEGUR_AJUST_SIT_PERIOD TO ems5.SEGUR_AJUST_SIT_PERIOD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_CCUSTO.
FOR EACH ems5hml.SEGUR_CCUSTO NO-LOCK:
    CREATE ems5.SEGUR_CCUSTO.
    BUFFER-COPY ems5hml.SEGUR_CCUSTO TO ems5.SEGUR_CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_CENAR_CTBL.
FOR EACH ems5hml.SEGUR_CENAR_CTBL NO-LOCK:
    CREATE ems5.SEGUR_CENAR_CTBL.
    BUFFER-COPY ems5hml.SEGUR_CENAR_CTBL TO ems5.SEGUR_CENAR_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_CTA_CORREN.
FOR EACH ems5hml.SEGUR_CTA_CORREN NO-LOCK:
    CREATE ems5.SEGUR_CTA_CORREN.
    BUFFER-COPY ems5hml.SEGUR_CTA_CORREN TO ems5.SEGUR_CTA_CORREN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_DEMONST_CTBL.
FOR EACH ems5hml.SEGUR_DEMONST_CTBL NO-LOCK:
    CREATE ems5.SEGUR_DEMONST_CTBL.
    BUFFER-COPY ems5hml.SEGUR_DEMONST_CTBL TO ems5.SEGUR_DEMONST_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGURPADRBCOTIPCHEQ.
FOR EACH ems5hml.SEGURPADRBCOTIPCHEQ NO-LOCK:
    CREATE ems5.SEGURPADRBCOTIPCHEQ.
    BUFFER-COPY ems5hml.SEGURPADRBCOTIPCHEQ TO ems5.SEGURPADRBCOTIPCHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_PADR_FLUXO_CX.
FOR EACH ems5hml.SEGUR_PADR_FLUXO_CX NO-LOCK:
    CREATE ems5.SEGUR_PADR_FLUXO_CX.
    BUFFER-COPY ems5hml.SEGUR_PADR_FLUXO_CX TO ems5.SEGUR_PADR_FLUXO_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_PLANO_CTA_CTBL.
FOR EACH ems5hml.SEGUR_PLANO_CTA_CTBL NO-LOCK:
    CREATE ems5.SEGUR_PLANO_CTA_CTBL.
    BUFFER-COPY ems5hml.SEGUR_PLANO_CTA_CTBL TO ems5.SEGUR_PLANO_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_PROJ_FINANC.
FOR EACH ems5hml.SEGUR_PROJ_FINANC NO-LOCK:
    CREATE ems5.SEGUR_PROJ_FINANC.
    BUFFER-COPY ems5hml.SEGUR_PROJ_FINANC TO ems5.SEGUR_PROJ_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_TALON_CHEQ.
FOR EACH ems5hml.SEGUR_TALON_CHEQ NO-LOCK:
    CREATE ems5.SEGUR_TALON_CHEQ.
    BUFFER-COPY ems5hml.SEGUR_TALON_CHEQ TO ems5.SEGUR_TALON_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_TIP_TRANS_CX.
FOR EACH ems5hml.SEGUR_TIP_TRANS_CX NO-LOCK:
    CREATE ems5.SEGUR_TIP_TRANS_CX.
    BUFFER-COPY ems5hml.SEGUR_TIP_TRANS_CX TO ems5.SEGUR_TIP_TRANS_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_UNID_CONTROL.
FOR EACH ems5hml.SEGUR_UNID_CONTROL NO-LOCK:
    CREATE ems5.SEGUR_UNID_CONTROL.
    BUFFER-COPY ems5hml.SEGUR_UNID_CONTROL TO ems5.SEGUR_UNID_CONTROL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_UNID_NEGOC.
FOR EACH ems5hml.SEGUR_UNID_NEGOC NO-LOCK:
    CREATE ems5.SEGUR_UNID_NEGOC.
    BUFFER-COPY ems5hml.SEGUR_UNID_NEGOC TO ems5.SEGUR_UNID_NEGOC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SEGUR_UNID_ORGAN.
FOR EACH ems5hml.SEGUR_UNID_ORGAN NO-LOCK:
    CREATE ems5.SEGUR_UNID_ORGAN.
    BUFFER-COPY ems5hml.SEGUR_UNID_ORGAN TO ems5.SEGUR_UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SER_FISC_NOTA.
FOR EACH ems5hml.SER_FISC_NOTA NO-LOCK:
    CREATE ems5.SER_FISC_NOTA.
    BUFFER-COPY ems5hml.SER_FISC_NOTA TO ems5.SER_FISC_NOTA.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_MOVIMEN_MODUL.
FOR EACH ems5hml.SIT_MOVIMEN_MODUL NO-LOCK:
    CREATE ems5.SIT_MOVIMEN_MODUL.
    BUFFER-COPY ems5hml.SIT_MOVIMEN_MODUL TO ems5.SIT_MOVIMEN_MODUL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.SIT_PERIOD_CTBL.
FOR EACH ems5hml.SIT_PERIOD_CTBL NO-LOCK:
    CREATE ems5.SIT_PERIOD_CTBL.
    BUFFER-COPY ems5hml.SIT_PERIOD_CTBL TO ems5.SIT_PERIOD_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TAB_LIVRE_EMSFIN.
FOR EACH ems5hml.TAB_LIVRE_EMSFIN NO-LOCK:
    CREATE ems5.TAB_LIVRE_EMSFIN.
    BUFFER-COPY ems5hml.TAB_LIVRE_EMSFIN TO ems5.TAB_LIVRE_EMSFIN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TABPRGSSIVIMPTORETID.
FOR EACH ems5hml.TABPRGSSIVIMPTORETID NO-LOCK:
    CREATE ems5.TABPRGSSIVIMPTORETID.
    BUFFER-COPY ems5hml.TABPRGSSIVIMPTORETID TO ems5.TABPRGSSIVIMPTORETID.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TALON_CHEQ.
FOR EACH ems5hml.TALON_CHEQ NO-LOCK:
    CREATE ems5.TALON_CHEQ.
    BUFFER-COPY ems5hml.TALON_CHEQ TO ems5.TALON_CHEQ.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_CLIEN.
FOR EACH ems5hml.TIP_CLIEN NO-LOCK:
    CREATE ems5.TIP_CLIEN.
    BUFFER-COPY ems5hml.TIP_CLIEN TO ems5.TIP_CLIEN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_FLUXO_CTA_CTBL.
FOR EACH ems5hml.TIP_FLUXO_CTA_CTBL NO-LOCK:
    CREATE ems5.TIP_FLUXO_CTA_CTBL.
    BUFFER-COPY ems5hml.TIP_FLUXO_CTA_CTBL TO ems5.TIP_FLUXO_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_FLUXO_FINANC.
FOR EACH ems5hml.TIP_FLUXO_FINANC NO-LOCK:
    CREATE ems5.TIP_FLUXO_FINANC.
    BUFFER-COPY ems5hml.TIP_FLUXO_FINANC TO ems5.TIP_FLUXO_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_FORNEC.
FOR EACH ems5hml.TIP_FORNEC NO-LOCK:
    CREATE ems5.TIP_FORNEC.
    BUFFER-COPY ems5hml.TIP_FORNEC TO ems5.TIP_FORNEC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_GRP_CTA_CTBL.
FOR EACH ems5hml.TIP_GRP_CTA_CTBL NO-LOCK:
    CREATE ems5.TIP_GRP_CTA_CTBL.
    BUFFER-COPY ems5hml.TIP_GRP_CTA_CTBL TO ems5.TIP_GRP_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_REPRES.
FOR EACH ems5hml.TIP_REPRES NO-LOCK:
    CREATE ems5.TIP_REPRES.
    BUFFER-COPY ems5hml.TIP_REPRES TO ems5.TIP_REPRES.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_TRANS_CX.
FOR EACH ems5hml.TIP_TRANS_CX NO-LOCK:
    CREATE ems5.TIP_TRANS_CX.
    BUFFER-COPY ems5hml.TIP_TRANS_CX TO ems5.TIP_TRANS_CX.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_TRANS_CX_ACR.
FOR EACH ems5hml.TIP_TRANS_CX_ACR NO-LOCK:
    CREATE ems5.TIP_TRANS_CX_ACR.
    BUFFER-COPY ems5hml.TIP_TRANS_CX_ACR TO ems5.TIP_TRANS_CX_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_TRANS_CX_CTA_CTBL.
FOR EACH ems5hml.TIP_TRANS_CX_CTA_CTBL NO-LOCK:
    CREATE ems5.TIP_TRANS_CX_CTA_CTBL.
    BUFFER-COPY ems5hml.TIP_TRANS_CX_CTA_CTBL TO ems5.TIP_TRANS_CX_CTA_CTBL.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_TRANS_CX_REAL_APB.
FOR EACH ems5hml.TIP_TRANS_CX_REAL_APB NO-LOCK:
    CREATE ems5.TIP_TRANS_CX_REAL_APB.
    BUFFER-COPY ems5hml.TIP_TRANS_CX_REAL_APB TO ems5.TIP_TRANS_CX_REAL_APB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TIP_UNID_ORGAN.
FOR EACH ems5hml.TIP_UNID_ORGAN NO-LOCK:
    CREATE ems5.TIP_UNID_ORGAN.
    BUFFER-COPY ems5hml.TIP_UNID_ORGAN TO ems5.TIP_UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRAD_FINALID_ECON_EXT.
FOR EACH ems5hml.TRAD_FINALID_ECON_EXT NO-LOCK:
    CREATE ems5.TRAD_FINALID_ECON_EXT.
    BUFFER-COPY ems5hml.TRAD_FINALID_ECON_EXT TO ems5.TRAD_FINALID_ECON_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRAD_FLUXO_EXT.
FOR EACH ems5hml.TRAD_FLUXO_EXT NO-LOCK:
    CREATE ems5.TRAD_FLUXO_EXT.
    BUFFER-COPY ems5hml.TRAD_FLUXO_EXT TO ems5.TRAD_FLUXO_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRAD_INDIC_ECON.
FOR EACH ems5hml.TRAD_INDIC_ECON NO-LOCK:
    CREATE ems5.TRAD_INDIC_ECON.
    BUFFER-COPY ems5hml.TRAD_INDIC_ECON TO ems5.TRAD_INDIC_ECON.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRAD_ORG_EXT.
FOR EACH ems5hml.TRAD_ORG_EXT NO-LOCK:
    CREATE ems5.TRAD_ORG_EXT.
    BUFFER-COPY ems5hml.TRAD_ORG_EXT TO ems5.TRAD_ORG_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRAD_PORTAD_EXT.
FOR EACH ems5hml.TRAD_PORTAD_EXT NO-LOCK:
    CREATE ems5.TRAD_PORTAD_EXT.
    BUFFER-COPY ems5hml.TRAD_PORTAD_EXT TO ems5.TRAD_PORTAD_EXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.TRANS_EDI.
FOR EACH ems5hml.TRANS_EDI NO-LOCK:
    CREATE ems5.TRANS_EDI.
    BUFFER-COPY ems5hml.TRANS_EDI TO ems5.TRANS_EDI.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T11690752PARAMGERALGLD.
FOR EACH ems5hml.T11690752PARAMGERALGLD NO-LOCK:
    CREATE ems5.T11690752PARAMGERALGLD.
    BUFFER-COPY ems5hml.T11690752PARAMGERALGLD TO ems5.T11690752PARAMGERALGLD.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T124260PARAMGERALCMG.
FOR EACH ems5hml.T124260PARAMGERALCMG NO-LOCK:
    CREATE ems5.T124260PARAMGERALCMG.
    BUFFER-COPY ems5hml.T124260PARAMGERALCMG TO ems5.T124260PARAMGERALCMG.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T29395490CALENDCOMIS.
FOR EACH ems5hml.T29395490CALENDCOMIS NO-LOCK:
    CREATE ems5.T29395490CALENDCOMIS.
    BUFFER-COPY ems5hml.T29395490CALENDCOMIS TO ems5.T29395490CALENDCOMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T30635522CCUSTO.
FOR EACH ems5hml.T30635522CCUSTO NO-LOCK:
    CREATE ems5.T30635522CCUSTO.
    BUFFER-COPY ems5hml.T30635522CCUSTO TO ems5.T30635522CCUSTO.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T386215PARAMEMPRESAPB.
FOR EACH ems5hml.T386215PARAMEMPRESAPB NO-LOCK:
    CREATE ems5.T386215PARAMEMPRESAPB.
    BUFFER-COPY ems5hml.T386215PARAMEMPRESAPB TO ems5.T386215PARAMEMPRESAPB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T5019889TRADORGEXT.
FOR EACH ems5hml.T5019889TRADORGEXT NO-LOCK:
    CREATE ems5.T5019889TRADORGEXT.
    BUFFER-COPY ems5hml.T5019889TRADORGEXT TO ems5.T5019889TRADORGEXT.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.T529044PARAMEMPRESACR.
FOR EACH ems5hml.T529044PARAMEMPRESACR NO-LOCK:
    CREATE ems5.T529044PARAMEMPRESACR.
    BUFFER-COPY ems5hml.T529044PARAMEMPRESACR TO ems5.T529044PARAMEMPRESACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNID_CONTROL_FINANC.
FOR EACH ems5hml.UNID_CONTROL_FINANC NO-LOCK:
    CREATE ems5.UNID_CONTROL_FINANC.
    BUFFER-COPY ems5hml.UNID_CONTROL_FINANC TO ems5.UNID_CONTROL_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNID_FEDERAC.
FOR EACH ems5hml.UNID_FEDERAC NO-LOCK:
    CREATE ems5.UNID_FEDERAC.
    BUFFER-COPY ems5hml.UNID_FEDERAC TO ems5.UNID_FEDERAC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNID_NEGOC.
FOR EACH ems5hml.UNID_NEGOC NO-LOCK:
    CREATE ems5.UNID_NEGOC.
    BUFFER-COPY ems5hml.UNID_NEGOC TO ems5.UNID_NEGOC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UNID_ORGAN.
FOR EACH ems5hml.UNID_ORGAN NO-LOCK:
    CREATE ems5.UNID_ORGAN.
    BUFFER-COPY ems5hml.UNID_ORGAN TO ems5.UNID_ORGAN.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_APB_MODUL_PERMIS.
FOR EACH ems5hml.USUAR_APB_MODUL_PERMIS NO-LOCK:
    CREATE ems5.USUAR_APB_MODUL_PERMIS.
    BUFFER-COPY ems5hml.USUAR_APB_MODUL_PERMIS TO ems5.USUAR_APB_MODUL_PERMIS.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_CHEQ_ACR_TERC.
FOR EACH ems5hml.USUAR_CHEQ_ACR_TERC NO-LOCK:
    CREATE ems5.USUAR_CHEQ_ACR_TERC.
    BUFFER-COPY ems5hml.USUAR_CHEQ_ACR_TERC TO ems5.USUAR_CHEQ_ACR_TERC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_FINANC.
FOR EACH ems5hml.USUAR_FINANC NO-LOCK:
    CREATE ems5.USUAR_FINANC.
    BUFFER-COPY ems5hml.USUAR_FINANC TO ems5.USUAR_FINANC.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_FINANC_ESTAB_ACR.
FOR EACH ems5hml.USUAR_FINANC_ESTAB_ACR NO-LOCK:
    CREATE ems5.USUAR_FINANC_ESTAB_ACR.
    BUFFER-COPY ems5hml.USUAR_FINANC_ESTAB_ACR TO ems5.USUAR_FINANC_ESTAB_ACR.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_FINANC_ESTAB_APB.
FOR EACH ems5hml.USUAR_FINANC_ESTAB_APB NO-LOCK:
    CREATE ems5.USUAR_FINANC_ESTAB_APB.
    BUFFER-COPY ems5hml.USUAR_FINANC_ESTAB_APB TO ems5.USUAR_FINANC_ESTAB_APB.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.USUAR_UNIV.
FOR EACH ems5hml.USUAR_UNIV NO-LOCK:
    CREATE ems5.USUAR_UNIV.
    BUFFER-COPY ems5hml.USUAR_UNIV TO ems5.USUAR_UNIV.
END.


DISABLE TRIGGERS FOR LOAD OF ems5.UTILIZ_CENAR_CTBL.
FOR EACH ems5hml.UTILIZ_CENAR_CTBL NO-LOCK:
    CREATE ems5.UTILIZ_CENAR_CTBL.
    BUFFER-COPY ems5hml.UTILIZ_CENAR_CTBL TO ems5.UTILIZ_CENAR_CTBL.
END.


*/
