CREATE ALIAS shmgadm    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgcex    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgcld    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgdbr    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgdis    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgfis    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgfro    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgind    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmginv    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgmfg    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgmnt    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgmrp    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgscm    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmgsop    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shmguni    FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shemsdca   FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shemsgra   FOR DATABASE shmgcad NO-ERROR.
CREATE ALIAS shems2oe   FOR DATABASE shmgcad NO-ERROR.


CREATE ALIAS mgadm  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcex  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgcld  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgdbr  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgdis  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgfis  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgfro  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgind  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mginv  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmfg  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmnt  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgmrp  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgscm  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mgsop  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS mguni  FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS emsgra FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS emsdca FOR DATABASE mgcad NO-ERROR.
CREATE ALIAS ems2oe FOR DATABASE mgcad NO-ERROR.

CREATE ALIAS shmovadm   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovdbr   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovdis   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovfis   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovfro   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovind   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovmfg   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shmovmnt   FOR DATABASE shmgmov NO-ERROR.
CREATE ALIAS shwmovdis  FOR DATABASE shmgmov NO-ERROR.

CREATE ALIAS movadm  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movdbr  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movdis  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movfis  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movfro  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movind  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmfg  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS movmnt  FOR DATABASE mgmov NO-ERROR.
CREATE ALIAS wmovdis FOR DATABASE mgmov NO-ERROR.


CREATE ALIAS shemsbas FOR DATABASE shemscad NO-ERROR.
CREATE ALIAS shemsedi FOR DATABASE shemscad NO-ERROR.
CREATE ALIAS shemsfin FOR DATABASE shemscad NO-ERROR.
CREATE ALIAS shemsuni FOR DATABASE shemscad NO-ERROR.
CREATE ALIAS shemsven FOR DATABASE shemscad NO-ERROR.
CREATE ALIAS shemsnam FOR DATABASE shemscad NO-ERROR.

CREATE ALIAS emsbas FOR DATABASE emscad NO-ERROR.
CREATE ALIAS emsedi FOR DATABASE emscad NO-ERROR.
CREATE ALIAS emsfin FOR DATABASE emscad NO-ERROR.
CREATE ALIAS emsuni FOR DATABASE emscad NO-ERROR.
CREATE ALIAS emsven FOR DATABASE emscad NO-ERROR.
CREATE ALIAS emsnam FOR DATABASE emscad NO-ERROR.

CREATE ALIAS shmovfin FOR DATABASE shemsmov NO-ERROR.

CREATE ALIAS movfin FOR DATABASE emsmov NO-ERROR.


CREATE ALIAS shdthrgst FOR DATABASE shhcm NO-ERROR.
CREATE ALIAS shdthrpmg FOR DATABASE shhcm NO-ERROR.
CREATE ALIAS shdthrpyc FOR DATABASE shhcm NO-ERROR.
CREATE ALIAS shdthrtma FOR DATABASE shhcm NO-ERROR.

CREATE ALIAS dthrgst FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrpmg FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrpyc FOR DATABASE hcm NO-ERROR.
CREATE ALIAS dthrtma FOR DATABASE hcm NO-ERROR.

CREATE ALIAS srmovben FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovcon FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovfi1 FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srweb    FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovfin FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srcadger FOR DATABASE shgp NO-ERROR.

CREATE ALIAS shsrmovben    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovcon    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovfi1    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrweb       FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovfin    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrcadger    FOR DATABASE gp NO-ERROR.


run _edit.p.

quit.




