/* Alias parte PROGRESS EMS5 */
CREATE ALIAS shemsbas FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsedi FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsfin FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsuni FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsven FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsinc FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shmovfin FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemscad FOR DATABASE shems5 NO-ERROR.
CREATE ALIAS shemsmov FOR DATABASE shems5 NO-ERROR.


/* Alias parte Oracle EMS5 */
CREATE ALIAS emsbas FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsedi FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsfin FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsuni FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsven FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsinc FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS movfin FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emscad FOR DATABASE ems5 NO-ERROR.
CREATE ALIAS emsmov FOR DATABASE ems5 NO-ERROR.

/* Alias dos Schema Holders GP*/
CREATE ALIAS srmovben FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovcon FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovfi1 FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srweb    FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srmovfin FOR DATABASE shgp NO-ERROR.
CREATE ALIAS srcadger FOR DATABASE shgp NO-ERROR.

CREATE ALIAS shsrmovben    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovcon    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovfi1    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrweb       FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrmovfin    FOR DATABASE gp NO-ERROR.
CREATE ALIAS shsrcadger    FOR DATABASE gp NO-ERROR.

RUN _edit.r.
quit.
