CREATE USER EMS506UNICOO IDENTIFIED BY EMS506UNICOO default tablespace ts_ems5;
GRANT CONNECT, RESOURCE, CREATE SESSION ,CREATE SYNONYM, CREATE VIEW, CREATE DATABASE LINK,CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO EMS506UNICOO;
