BEGIN 
  FOR X IN (SELECT 'GRANT ALL ON ' || OBJECT_NAME || ' TO &OWNER' COMANDO 
              FROM USER_OBJECTS 
             WHERE OBJECT_TYPE IN 
                   ('FUNCTION', 'PROCEDURE', 'TABLE', 'SEQUENCE')) LOOP 
    EXECUTE IMMEDIATE X.COMANDO; 
  END LOOP; 
END;
/
