prompt PL/SQL Developer import file
prompt Created on quinta-feira, 28 de abril de 2016 by totvs
set feedback off
set define off
prompt Loading REM_INFORMACAO...
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (1, 'Nome do contratante', 'NOCONTRATANTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (9, 'Bairro', 'BAIRRO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (10, 'Cidade', 'CIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (11, 'Estado', 'CDESTADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (12, 'C.E.P.', 'CEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (13, 'Caixa Postal', 'CXPOSTAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (14, 'Número do Telefone 1', 'NRTELEFONE1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (15, 'Número do Ramal do Telefone 1', 'NRRAMAL1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (16, 'Número do Telefone 2', 'NRTELEFONE2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (17, 'Número do Ramal do Telefone 2', 'NRRAMAL2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (18, 'Inscrição Estadual', 'INSCESTADUAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (19, 'Número do Grupo de Clientes', 'NRGRUPO_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (20, 'Código da junta comercial', 'CDJUNTA_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (21, 'Valor da Renda ou Faturamento Mensal', 'VLRENDA_FAT_MENSAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (22, 'Valor do Capital Social', 'VLCAPITAL_SOCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (23, 'Número da identidade', 'CDIDENTIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (24, 'Nome do Pai', 'NOPAI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (25, 'Nome da Mãe', 'NOMAE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (26, 'Nome do cônjuge', 'NOCONJUGE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (27, 'Código da Situação da análise de Crédito', 'CDSITUACAO_CREDITO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (28, 'Data da análise de crédito', 'DTSITUACAO_CREDITO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (29, 'Nome para Cartão Magnético', 'NOCARTAO_MAGNETICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (30, 'Nome Internacional', 'NOINTERNACIONAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (31, 'Código da Unidade do Grupo do Contratante', 'NRUNIDADE_GRUPO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (32, 'Grupo do contratante', 'CDGRUPO_CONTRATANTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (33, 'Complemento do Grupo do Contratante', 'COMPLEMENTO_GRUPO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (34, 'Local de Trabalho', 'LOCAL_TRABALHO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (35, 'Endereço Comercial', 'ENDERECO_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (36, 'Bairro do Endereço Comercial', 'BAIRRO_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (37, 'Cidade do Endereço Comercial', 'CIDADE_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (38, 'Estado do Endereço Comercial', 'CDESTADO_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (39, 'C.E.P. do Endereço Comercial', 'CEP_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (40, 'Número do Telefone Comercial', 'NRTELEFONE_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (41, 'Número do Ramal do Telefone Comercial', 'NRRAMAL_COMERCIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (42, 'Nome do Fornecedor', 'NOFORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (43, 'Endereço do Fornecedor', 'ENDERECO_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (44, 'Bairro do Fornecedor', 'BAIRRO_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (45, 'Cidade do Fornecedor', 'CIDADE_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (46, 'Estado do Fornecedor', 'CDESTADO_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (47, 'C.E.P. do Fornecedor', 'CEP_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (2, 'Tipo de pessoa (F-Física / J-Jurídica)', 'TPPESSOA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (3, 'Número do CGC ou CPF', 'CGC_CPF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (4, 'Nome abreviado', 'NOABREVIADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (5, 'Data de Nascimento ou de Fundação', 'DTNASCIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (6, 'Código do estado civil', 'CDESTADO_CIVIL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (7, 'Sexo', 'CDSEXO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (8, 'Endereço', 'ENDERECO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (273, 'Informações Específicas 2', 'TXINF_ESPECIFICAS2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (274, 'Informações Específicas 3', 'TXINF_ESPECIFICAS3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (275, 'Informações Específicas 4', 'TXINF_ESPECIFICAS4', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (276, 'Contrato Antigo', 'CDCONTRATO_ANTIGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (277, 'Carteira Antiga', 'NRCARTEIRA_ANTIGA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (278, 'Código da unidade de origem', 'NRUNIDADE_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (279, 'Código de identificação do beneficiário na unidade origem', 'NRIDENTIF_UNI_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (280, 'Código do Plano origem', 'CDPLANO_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (281, 'Nome do Plano origem', 'NOPLANO_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (282, 'Número da Carteira Antiga do Responsável', 'NRCARTEIRA_ANTIGA_RESP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (283, 'Padrão de Cobertura Anterior', 'CDPADRAO_COBERTURA_ANT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (284, 'Data de Alteração para Exportação do Produto', 'DTALTER_EXPORT_PRODUTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (285, 'Data do Falecimento do Titular', 'DTFALECIMENTO_TITULAR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (286, 'Data da Atualização da Carência', 'DTATUALIZ_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (287, 'Usuário que efetuou atualização da carência', 'CDUSU_ATUALIZ_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (288, 'Indicador Bonifica/Penaliza Carência', 'AOBONIF_PENAL_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (289, 'Número de Dias de Bonificação para o Beneficiário', 'NRDIAS_BONIFICACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (290, 'Indica se o fator de participação será cobrado', 'AOCOBRA_FATOR_PARTICIP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (291, 'Data de início do Vinculo do Beneficiário com a Unidade', 'DTVINCULO_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (292, 'Data de fim do Seguro assistencial do Beneficiário', 'DTFIM_SEG_ASSIST_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (293, 'Mês de referência da última Fatura', 'NRULTIMO_MES_FATURADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (294, 'Ano de referência da última Fatura', 'NRULTIMO_ANO_FATURADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (295, 'Departamento da Empresa', 'NRDEPARTAMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (296, 'Seção da Emprea', 'NRSECAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (297, 'Setor da Empresa', 'NRSETOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (298, 'Carteira de Trabalho', 'CDCARTEIRA_TRABALHO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (299, 'Data da Primeira Consulta', 'DTPRIMEIRA_CONSULTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (300, 'Código do Motivo do Cancelamento', 'NRMOTIVO_CANC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (301, 'Função do Beneficiário', 'NRFUNCAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (302, 'Cartão Nacional de Saúde do Beneficiário', 'NRCARTAO_NACIO_SAUDE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (303, 'Segmento Assistêncial do Beneficiário', 'NRSEGMENTO_ASSIT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (304, 'Data Inclusão Unidade Origem Benef. Repassados', 'DTINCLU_UNI_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (305, 'Código de Identificação do responsável na Unidade Origem', 'NRIDENT_RESP_UNI_ORI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (306, 'Código do Registro do Plano ANS', 'NRREGISTRO_PLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (307, 'Código do Vendedor', 'NRVENDEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (308, 'Código do Registro Plano Operadora', 'CDREG_PLANO_OPERADORA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (309, 'Motivo da Inclusão do Beneficiário', 'CDMOTIVO_INCLUSAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (310, 'Nome Completo do Beneficiário', 'NOBENEFICIARIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (311, 'Número do produto da operadora origem', 'NRPRODUTO_OPER_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (312, 'Código de Controle Operacional (CCO)', 'NRCCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (313, 'Número do Módulo Cadastrado', 'NRMODULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (314, 'Data início do Módulo', 'DTINI_MODULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (315, 'Data de cancelamento do Módulo', 'DTCANC_MODULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (316, 'Unidade de Negociação', 'NRUNI_NEGOCIACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (317, 'Data de Intercâmbio', 'DTINTERCAMBIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (318, 'Indica se a Taxa Inscri. do Benef. Será Repassada', 'AOTAXA_INSC_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (319, 'Indica se a Taxa Inscri. do Benef. Deve ser Cobrada', 'AOTAXA_INSC_COBRADA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (320, 'Mês do último repasse do Beneficiário', 'NRULTIMO_MES_CALCULADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (321, 'Ano do último repasse do Beneficiário', 'NRULTIMO_ANO_CALCULADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (322, 'Data de Saída do Repasse para a Unidade', 'DTSAIDA_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (323, 'Identificação da unidade de negocioação', 'NRIDENTIF_UNI_NEGOCIACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (324, 'Unidade de Atendimento', 'NRUNI_ATENDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (325, 'Indica se é procedimento ou insumo', 'AOPROCEDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (326, 'Código do procedimento ou insumo', 'NRPROC_INSU', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (327, 'Tipo de Insumo', 'TPINSUMO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (328, 'Tabela de moeda e carência', 'CDTAB_MOE_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (329, 'Indica acrescimo/restrição cobert. Ou sobre.dias carência ', 'NRCARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (330, 'Data de início de vigência', 'DTINI_VIGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (331, 'Data de fim de vigência', 'DTFIM_VIGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (332, 'Número de dias de validade do procedimento', 'NRDIAS_VALID_PROCEDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (333, 'Data de intercâmbio Atendimento', 'DTINTERC_ATEND', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (334, 'Data de Saída do Repasse Unidade Atendimento', 'DTSAIDA_REPASSE_ATEND', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (335, 'Módulo de Cobertura', 'NRMOD_COBERTURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (336, 'Data de Cancelamento da Cobertura Especial', 'DTCANC_COBERTURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (337, 'CPF/CGC Contratante', 'CGC_CPF_CONTRATANTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (338, 'Número da inscrição do contratante de Origem', 'NRINSC_CONTRAT_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (339, 'Tipo de Plano', 'TPPLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (340, 'Tipo de Vencimento', 'TPVENCIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (341, 'Dia de Vencimento', 'NRDIA_VENCIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (342, 'Indica Inicio de Validade do Plano de Saúde', 'AOINI_VALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (343, 'Convênios  relacionados Modalidade/Plano/Tipo/Forma Pagto.', 'NRCONVENIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (344, 'Tipos de Participacao', 'TPPARTICIPACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (345, 'Tabelas de Preco dos Planos', 'CDTAB_PRECO_PLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (346, 'Percentual de Acrescimo sobre a mensalidade', 'VLPERC_ACRESC_MENSALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (347, 'Data Limite de Validade do Acrescimo sobre a mensalidade', 'DTLIM_ACRESC_MENSALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (348, 'Percentual de Acrescimo sobre a inscricao', 'VLPERC_ACRESC_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (349, 'Data Limite de Validade do Acrescimo sobre a inscricao', 'DTLIM_ACRESC_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (350, 'Percentual de Desconto sobre a mensalidade', 'VLPERC_DESC_MENSALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (351, 'Data Limite de Validade do Desconto sobre a mensalidade', 'DTLIM_DESC_MENSALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (352, 'Percentual de Desconto sobre a inscricao', 'VLPERC_DESC_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (353, 'Data Limite de Validade do Desconto sobre a inscricao', 'DTLIM_DESC_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (354, 'Percentual de Desconto Taxa Prestador', 'VLPERC_DESC_TAXA_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (355, 'Percentual de Desconto Taxa Administração Credenciado', 'VLPERC_DESC_TAXA_ADM_CREDEN', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (356, 'Tabela Qtd de Moedas Pagamento', 'CDTAB_QTD_MOEDAS_PAGTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (357, 'Codigo do funcionario sera informado', 'AOMASCARA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (358, 'Formato Padrao do Codigo do Funcionario', 'TXMASCARA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (359, 'Indicador se a proposta possui faixa etaria especial', 'AOFAIXA_ETARIA_ESPEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (360, 'Informe se a proposta tera diferenca de cobertura do plano', 'AOCOBERTURA_ESPEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (361, 'Informe se calculo de Moedas e Cobertura sera por prestador', 'AOCONSID_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (362, 'Informe considera taxa intercambio Cobranca proc. Cust.Oper', 'AOCONSID_TAXA_CO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (363, 'Informe o percentual sobre os usos indevidos', 'VLPERC_USO_INDEVIDO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (364, 'Informe se o contratante (P.J.)possui medico na empresa', 'AOMEDICO_EMPRESA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (365, 'Data inicio contrato', 'DTINI_PROPOSTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (366, 'Data cancelamento contrato (contrato cancelado)', 'DTCANC_PROPOSTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (367, 'CGC/CPF Contratante Origem', 'CGC_CPF_CONTRAT_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (368, 'Tipo de Pessoa contratante origem', 'TPPESSOA_ORIGEM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (369, 'Valor da Proposta', 'VLPROPOSTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (370, 'Tabela Qtd de Moedas Cobranca', 'CDTAB_QTD_MOEDAS_COBR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (371, 'Documento Identificacao Benef. (S-Cartao/N-Carteira)', 'AODOC_IDENT_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (372, 'Utiliza Tabela de Cobranca Diferente de Pagamento', 'AOTAB_DIFER_COBR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (373, 'Percentual Promocional sobre Taxa de Inscricao', 'VLPERC_DESC_PROM_TX_INSC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (374, 'Data de Validade do Desconto Promocional s/taxa de Inscricao', 'DTVAL_DESC_PRO_TX_INSC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (375, 'Percentual Promocional sobre a Mensalidade', 'VLPERC_DESC_PROC_MENS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (376, 'Data de Validade do Desconto Promocional s/Mensalidade', 'DTVAL_DESC_PRO_MENS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (377, 'Indica se a proposta esta atuando com Seg Assistencial', 'AOPROP_SEG_ASSIST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (378, 'Data Prevista termino da Utilizacao do Seguro Assistencial', 'DTFIM_SEG_ASSIST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (379, 'Faturar Proposta Seguro Assistencial', 'AOFAT_PROP_SEG_ASSIT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (380, 'Indica se é possivel alterar indicador particip. Benef.', 'AOALTERA_PARTICIP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (381, 'Indica se possivel alterar indic. Cobr. taxa Inscri. benef.', 'AOALTERA_TX_INSCRI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (382, 'Indica se possivel alterar inicio valid. do Benef. p/ mov.', 'AOVALID_BENEF_MOVIMENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (383, 'indica se fatura sera emitida p/ o contratante ou sinistrado', 'NRCOBR_CONTRAT_SINIS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (384, 'Mes do ultimo reajuste da proposta', 'NRULTIMO_MES_REAJUSTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (385, 'Ano do ultimo reajuste da proposta', 'NRULTIMO_ANO_REAJUSTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (386, 'Percentual do ultimo  reajuste da proposta', 'VLPERC_ULTIMO_REAJUSTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (387, 'Codigo do Registro do Plano na Susep', 'NRREGISTRO_PLANO_SUSEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (388, 'Indica se possivel prorrogar inicio da valid. Benef. p/ mov.', 'AOVAL_PRORROG_BENEF_MOV', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (389, 'Indicador para verificar se proposta eh regulamentada', 'AOPROP_REGULAMENTADA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (390, 'Quantidade de dias, meses ou anos de validade do termo', 'QTD_VALID_TERMO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (391, 'Unidade da validade do termo', 'CDUNID_VALID_TERMO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (392, 'Quantidade de dias, meses ou anos de validade da carteira', 'QTD_VALID_CARTEIRA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (393, 'Unidade da validade da carteira', 'CDUNID_VALID_CARTEIRA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (394, 'Quantidade de dias, meses ou anos de validade do cartao', 'QTD_VALID_CARTAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (395, 'Unidade da validade do cartao', 'CDUNID_VALID_CARTAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (396, 'Indica o tipo de contratacao determinado pela ANS ', 'TPCONTRATACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (397, 'Tipo de Natureza Juridica da Contratacao', 'TPNATUREZA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (398, 'Tipo Valid Doc Identif p/ benef fora de grau/faixa etaria', 'TPVALID_DOC_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (399, 'Numero do Oficio para Reajuste dos planos das Operadoras', 'CDOFICIO_REAJUSTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (400, 'Indicador para o tipo de registro de plano', 'NRINDIC_REG_PLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (401, 'Módulo de Plano x Modulo Cobertura', 'NRMOD_PLANO_COBERTURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (402, 'Formas de Pagamento Módulo', 'NRFORMA_PGTO_MODULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (403, 'Informe a carencia do modulo', 'AOCARENCIA_MODULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (404, 'Informe o responsavel pela autorizacao', 'AORESP_AUTORIZ', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (405, 'Informe se o modulo sera cobertura obrigatoria', 'AOCOBERTURA_OBRIG', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (406, 'Informe onde sera feita a cobranca da participacao', 'NRCOBRA_PARTICIPACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (407, 'Nr dias bonificacao/penalizacao conforme indic. carencia', 'NRDIAS_BONIF_PEN_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (408, 'Quantidade da Carencia Eletiva para o Modulo', 'QTDCARENCIA_ELETIVA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (409, 'Quantidade da Carencia Urgencia para o Modulo', 'QTDCARENCIA_URGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (410, 'Indica como sera o controle da carencia de procedimento', 'NRIND_CARENCIA_PROCED', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (411, 'Indica como sera o controle da carencia de insumo', 'NRIND_CARENCIA_INSUMO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (412, 'Faixa Etaria do Grau de Parentesco', 'NRFAIXA_ETARIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (413, 'Idade minima do grau de parentesco', 'NRIDADE_MIN', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (414, 'Idade maxima do do grau de parentesco', 'NRIDADE_MAX', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (415, 'Fator multiplicador do Plano', 'VLFAT_MULT_MENSALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (416, 'multiplicador da taxa de inscricao', 'VLFAT_MULT_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (417, 'Codigo do Plano de Saude', 'NRPLANO_SAUDE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (418, 'Forma de Pagamento', 'NRFORMA_PGTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (419, 'Indica a unid medida Carencia Unid origem X Unid repassada', 'CDUNIDADE_CARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (420, 'Indica qto tempo o repasse ficara de carencia na Unidade', 'QTDCARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (421, 'Tabela de Preco do Plano Negociacao', 'CDTAB_PRECO_PLANO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (422, 'Tabela Quantidade Moedas Pagamento Negociacao', 'CDTAB_QTD_MOEDAS_PAGTO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (423, 'Tipos e Dias de Vencimento Negociacao', 'TPVENCIMENTO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (424, 'Indica se a valorizacao utiliza a estrutura repasse', 'AOTPVALORIZ_CUSTO_OPER', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (425, 'Percentual de acrescimo na inscricao de repasse', 'VLPERC_ACRESC_INSC_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (426, 'Percentual de desconto da inscricao de repasse', 'VLPERC_DESC_INSC_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (427, 'Percentual de Desconto do Repasse (Mensalidade)', 'VLPERC_DESC_MENSAL_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (428, 'Percentual de Acrescimo do Repasse (Mensalidade)', 'VLPERC_ACRESC_MENSAL_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (429, 'Local da Impressao da Carteira Origem(SIM) / Destino(NAO)', 'AOIMPRIME_CARTEIRA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (430, 'Onde sera realizado Calc Repasse Orig(SIM) Destino (NAO)', 'AOCALCULO_VALOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (431, 'Indicador se a negociacao sofrera ou nao calculo', 'CDINDIC_CALCULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (432, 'Data Inicio da negocicao', 'DTINICIO_NEGOCIACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (433, 'Data de cancelamento da Negociacao', 'DTCANC_NEGOCIACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (434, 'Mes de ultimo calculo de repasse para negociacao', 'NRULTIMO_MES_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (435, 'Ano de ultimo calculo de repasse para negociacao', 'NRULTIMO_ANO_REPASSE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (436, 'Codigo do padrao de cobertura Negociacao', 'CDPADRAO_COBERTURA_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (437, 'Percent acrescimo axa inscricao plano de Saude Cobert.', 'VLPERC_ACRESC_INSC_COBERT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (438, 'Percent desconto taxa inscricao plano de Saude Cobert.', 'VLPERC_DESC_INSC_COBERT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (439, 'Percentual de acrescimo sobre a mensalidade Cobert.', 'VLPERC_ACRESC_MENS_COBERT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (440, 'Percentual de desconto sobre a mensalidade Cobert.', 'VLPERC_DESC_MENS_COBERT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (441, 'Numero de dias de Bonificacao Cobertura', 'NRDIAS_BONIFIC_COBERT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (442, 'Descricao do Campo-1', 'TXCAMPO1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (443, 'Mascara de edicao do campo-1', 'TXMASCARA1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (444, 'Indica se o campo-1 obriga a digitacao', 'AOOBRIGA_DIGIT1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (445, 'Indica se os dados devem ser verificados', 'AOCONSISTE_DADOS1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (446, 'Descricao do Campo-2', 'TXCAMPO2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (447, 'Mascara de edicao do campo-2', 'TXMASCARA2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (448, 'Indica se o campo-2 obriga a digitacao', 'AOOBRIGA_DIGIT2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (449, 'Indica se os dados devem ser verificados', 'AOCONSISTE_DADOS2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (450, 'Descricao do Campo-3', 'TXCAMPO3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (451, 'Mascara de edicao do campo-3', 'TXMASCARA3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (452, 'Indica se o campo-3 obriga a digitacao', 'AOOBRIGA_DIGIT3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (453, 'Indica se os dados devem ser verificados', 'AOCONSISTE_DADOS3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (454, 'Descricao do Campo-4', 'TXCAMPO4', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (455, 'Mascara de edicao do campo-4', 'TXMASCARA4', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (456, 'Indica se o campo-4 obriga a digitacao', 'AOOBRIGA_DIGIT4', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (457, 'Indica se os dados devem ser verificados', 'AOCONSISTE_DADOS4', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (458, 'Codigo do Modulo Procedimentos Especiais', 'NRMOD_PROC_ESPEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (459, 'Codigo do procedimento', 'NRPROCEDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (460, 'Indicador de cobertura', 'AOIND_COBERTURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (461, 'Data de inicio do contrato', 'DTINI_CONTRATO_PROC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (462, 'Data de cancelamento do procedimento', 'DTCANC_PROCEDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (463, 'Quantidade do procedimento', 'QTDPROCEDIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (464, 'Descricao Detalhada da Funcao', 'TXDETAL_FUNCAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (465, 'Plano de Saúde Negociação', 'NRPLANO_SAUDE_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (466, 'Forma de Pagamento Negociação', 'NRFORMA_PAGTO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (467, 'Estado do endereço do prestador', 'CDESTADO_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (468, 'Telefone 1 do prestador', 'NRTELEFONE1_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (469, 'Receber malote do endereço do prestador', 'AORECEBE_MALOTE_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (470, 'Endereço do prestador', 'ENDERECO_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (471, 'Ramal do telefone do prestador', 'NRRAMAL2_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (472, 'Cidade do prestador', 'CDCIDADE_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (473, 'Código Nacional de estabelecimento de saúde do prestador', 'CDCNES_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (474, 'Bairro do prestador', 'BAIRRO_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (475, 'CEP do prestador', 'CEP_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (476, 'Ramal 2 do telefone do prestador', 'NRRAMAL1_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (477, 'Telefone 2 do prestador', 'NRTELEFONE2_PREST', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (478, 'Último ano faturado do módulo do beneficiario', 'NRULTIMO_ANO_FATURADO_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (479, 'Número de dia bonificado do módulo do beneficiario', 'NRDIAS_BONIFICACAO_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (480, 'Número do motivo de cancelamento do módulo do benef.', 'NRMOTIVO_CANC_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (481, 'Indicador bonifica/penaliza carencia do módulo', 'AOBONIF_PENAL_CARENCIA_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (482, 'Último mês faturado do módulo do beneficiario', 'NRULTIMO_MES_FATURADO_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (483, 'Indicador se módulo do beneficiario possui carência', 'AOCARENCIA_BENEF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (484, 'Tipo de plano da negociação', 'TPPLANO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (485, 'Dia do vencimento da negociação', 'NRDIA_VENCIMENTO_NEGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (486, 'Codigo grupo procedimento AMB', 'CDGRUPO_PROCEDIMENTO_AMB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (487, 'Digito verificador procedimento AMB ', 'NRDIGITO_PROC_AMB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (488, 'Codigo do Insumo', 'NRINSUMO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (489, 'Quantidade autorizada', 'QTD_AUTORIZADA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (490, 'Data da autorizacao', 'DTAUTORIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (491, 'Data da primeira autorizacao', 'DTPRIMEIRA_AUTORIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (492, 'Quantidade realizada', 'QTD_REALIZADA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (493, 'Data da realizacao', 'DTREALIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (494, 'Data da primeira realizacao', 'DRPRIMEIRA_REALIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (495, 'Codigo da carteira antiga', 'CDCARTEIRA_ANTIGA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (496, 'Participa Qualiss', 'AOPARTICIP_QUALIS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (497, 'Participa NOTIVISA', 'AOPARTICIP_NOTIVISA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (498, 'Envia Cadu', 'AOENVIA_CADU', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (499, 'Data inicio validade Especialidade', 'DTINIC_VINC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (500, 'Data fim validade Especialidade', 'DTFIN_VINC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (48, 'Número do Telefone do Fornecedor', 'NRTELEFONE_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (49, 'Número do Ramal do Telefone do Fornecedor', 'NRRAMAL_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (50, 'Contato do Fornecedor', 'CONTATO_FORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (51, 'Nome do Cliente', 'NOCLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (52, 'Endereço do Cliente', 'ENDERECO_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (53, 'Bairro do Cliente', 'BAIRRO_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (54, 'Cidade do Cliente', 'CIDADE_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (55, 'Estado do Cliente', 'CDESTADO_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (56, 'C.E.P do Cliente', 'CEP_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (57, 'Número do Telefone do Cliente', 'NRTELEFONE_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (58, 'Número do Ramal do Telefone do Cliente', 'NRRAMAL_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (59, 'Contato do Cliente', 'CONTATO_CLIENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (60, 'Nome do Banco', 'NOBANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (61, 'Endereço do Banco', 'ENDERECO_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (62, 'Bairro do Banco', 'BAIRRO_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (63, 'Cidade do Banco', 'CIDADE_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (64, 'Estado do Banco', 'CDESTADO_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (65, 'C.E.P. do Banco', 'CEP_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (66, 'Número do Telefone do Banco', 'NRTELEFONE_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (67, 'Número do Ramal do Telefone do Banco', 'NRRAMAL_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (68, 'Contato do Banco', 'CONTATO_BANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (69, 'Indica se possui moradia própria (S-Sim/N-Não)', 'AOMORADIA_PROPRIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (70, 'Tipo da Moradia (1-Casa/2-Apartamento/3-Outros)', 'TPMORADIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (71, 'Tipo da Construção (1-Alvenaria/Madeira/Mista)', 'TPCONSTRUCAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (72, 'Local da Moradia', 'LOCAL_MORADIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (73, 'Valor da Moradia', 'VLMORADIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (74, 'Indica se possui terreno (S-Sim/N-Não)', 'AOPOSSUI_TERRENO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (75, 'Local do Terreno', 'LOCAL_TERRENO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (76, 'Valor do Terreno', 'VLTERRENO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (77, 'Indica se possui veículo (S-Sim/N-Não)', 'AOPOSSUI_VEICULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (78, 'Marca do Veículo', 'MARCA_VEICULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (79, 'Modelo do Veículo', 'MODELO_VEICULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (80, 'Ano de fabricação do Veículo', 'ANO_FABRICACAO_VEICULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (81, 'Valor do Veículo', 'VLVEICULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (82, 'Código do portador', 'NRPORTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (83, 'Modalidade', 'NRMODALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (84, 'Código do Banco', 'NRBANCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (85, 'Número da Agência', 'CDAGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (86, 'Número da Conta Corrente do Portador', 'CDCONTA_CORRENTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (87, 'Endereço do Correio Eletrônico', 'EMAIL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (88, 'Número Geração Fatura', 'NRGERACAO_FATURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (89, 'Contato 1', 'CONTATO1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (90, 'Contato 2', 'CONTATO2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (91, 'Rua de Cobrança', 'ENDERECO_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (92, 'Bairro de Cobrança', 'BAIRRO_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (93, 'Cidade de Cobrança', 'CIDADE_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (94, 'UF de Cobrança', 'CDESTADO_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (95, 'Cep de Cobrança', 'CEP_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (96, 'Caixa Postal de Cobrança', 'CXPOSTAL_COBRANCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (97, 'Indicador de geração de aviso de débito', 'AOGERA_AVISO_DEBITO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (98, 'Indicador de emissão de boleto', 'AOEMITE_BOLETO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (99, 'Indicador de retenção de imposto', 'AORETEM_IMPOSTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (100, 'Indicador de necessidade de acompanhamento', 'AONECESSITA_ACOMP_SPC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (101, 'Indicador Separa Faturas de Custo Operacional', 'AOSEPARA_FATURA_CUST_OP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (102, 'Indicador Separa Faturas de Participação', 'AOSEPARA_FATURA_PART', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (103, 'Indicador Insumos Credenciados de Custo Operacional', 'AOINSUMOS_CREND_CUST_OP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (104, 'Indicador Insumos Credenciados de Custo de Participação', 'AOINSUMOS_CREND_CUST_PART', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (105, 'Indicador Utiliza Evento', 'AOUTILIZA_EVENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (106, 'Número do cadastro especial utilizado pelo INSS', 'CDCEI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (107, 'Dígito da agência', 'CDDIGITO_AGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (108, 'Dígito da conta corrente', 'CDDIGITO_CONTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (109, 'Natureza do Documento de Indentificação', 'NATUREZA_DOC_IDENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (110, 'Orgão Emissor do Documento de Identificação', 'ORGAO_EMISSOR_IDENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (111, 'País de Emissão do Documento de Identificação', 'PAIS_EMISSOR_IDENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (112, 'Estado Emissor do Documento de Identificação', 'CDESTADO_EMISSOR_IDENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (113, 'Data de Emissão do Documento de Identificação', 'DTEMISSAO_DOC_IDENT', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (114, 'Nacionalidade', 'NACIONALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (115, 'Código Brasileiro de Ocupação/Ramo de Atividade', 'NRCBO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (116, 'Código da Unidade', 'NRUNIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (117, 'Código que Identifica o Prestado', 'CDPRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (118, 'Nome do Prestador', 'NOPRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (119, 'Grupo do Prestador', 'NRGRUPO_PRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (120, 'Indica se o prestador possui formação médica', 'AOMEDICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (121, 'Indica se o prestador é um médico cooperado', 'AOCREDENCIADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (122, 'Unidade Seccional', 'NRUNIDADE_SECCIONAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (123, 'Conselho', 'CDCONSELHO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (124, 'UF do conselho a que o Prestador está associado', 'CDESTADO_CONSELHO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (125, 'Código do Registro do Prestador associado ao conselho', 'NRCRM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (126, 'Código de fornecedor referente ao Prestador', 'CDFORNECEDOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (127, 'Data da inclusão do Prestador', 'DTINCLU_PRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (128, 'Data da exclusão do Prestador', 'DTEXCLU_PRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (129, 'Número da inscrição do credenciado na unidade', 'NRINSCRI_PRESTADOR', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (130, 'Situação do credenciado junto ao Sindicato', 'CDSITUACAO_SINDICAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (131, 'Fator de produtividade do Prestador', 'VLFATOR_PRODUTIVIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (132, 'Indica se o Prestador possui alvará de localização', 'AOPOSSUI_ALVARA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (133, 'Indica se possui registro do INSS', 'AOREGISTRO_INSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (134, 'Indica se o Prestador possui diploma', 'AOPOSSUI_DIPLOMA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (135, 'Especialidade de Residência', 'NRESPEC_RESIDENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (136, 'Especialidade do Título', 'NRESPEC_TITULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (137, 'Indica se recebe malote', 'AORECEBE_MALOTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (138, 'Indica prestador tem Vínculo empregatício c/outra empresa', 'AOPOSSUI_VINC_EMPREGATICIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (139, 'Ultimo mês cobrado INSS', 'NRULTIMO_MES_INSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (140, 'Indica se Prestador representa uma unidade', 'AOREPRESENTA_UNIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (141, 'Código do horário de urgência', 'NRHORARIO_URGENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (142, 'Indica se recolhe INSS', 'AORECOLHE_INSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (143, 'Indica se o Prestador recolhe participação (Fator moderador)', 'AORECOLHE_PARTICIPACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (144, 'Observação 1', 'TXOBSERVACAO1', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (145, 'Observação 2', 'TXOBSERVACAO2', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (146, 'Observação 3', 'TXOBSERVACAO3', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (147, 'Indica se o prestador calcula imposto de renda', 'AOCALC_IMPOSTO_RENDA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (148, 'Indica onde vai incidir o imposto de renda', 'NRINDICE_IRRF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (149, 'Indica se vai ser calculado adiantamento da produção', 'AOCALC_ADIANTAMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (150, 'Data do calculo do adiantamento', 'DTCALC_ADIANTAMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (151, 'Número de dependentes (informado apenas para pessoa física)', 'NRDEPENDENTES', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (152, 'Indica se títulos do pagamento será para o RH', 'AOPAGTO_RH', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (153, 'Tipo de fluxo', 'TPFLUXO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (154, 'Imposto', 'IMPOSTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (155, 'Código de classificação imposto', 'CDCLASSIFIC_IMPOSTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (156, 'Número do PIS/PASEP', 'NRPIS_PASEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (157, 'Número da Inscrição do INSS', 'NRINSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (158, 'Indica se o prestador divide honorário', 'AODIVIDE_HONORARIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (159, 'Indica se deve ser calculado COFINS', 'AOCALC_COFINS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (160, 'Indica se deve ser calculado PIS/PASEP', 'AOCALC_PIS_PASEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (161, 'Indica se deve ser calculado CSLL', 'AOCALC_CSLL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (162, 'Código imposto COFINS', 'CDCOFINS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (163, 'Código imposto PIS/PASEP', 'CDPIS_PASEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (164, 'Código imposto CSLL', 'CDCSLL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (165, 'Classificação imposto COFINS', 'CDCLASSIFIC_COFINS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (166, 'Classificação imposto PIS/PASEP', 'CDCLASSIFIC_PIS_PASEP', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (167, 'Classificação imposto CSLL', 'CDCLASSIFIC_CSLL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (168, 'Código imposto INSS', 'CDINSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (169, 'Classificação imposto INSS', 'CDCLASSIFIC_INSS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (170, 'Indica se deve ser calculado ISS.', 'AOCALC_ISS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (171, 'Código imposto ISS', 'CDISS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (172, 'Classificação imposto ISS', 'CDCLASSIFIC_ISS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (173, 'Indica se deduz o ISS da produção dos prestadores ou não', 'AODEDUZ_ISS_PRODUCAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (174, 'Indica número de dias de validade p/ reconsulta c/prestador', 'NRDIAS_VALID_RECONS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (175, 'Número do código do tipo de pagamento', 'CDFORMA_PAGTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (176, 'Indica se será calculado PISPASEP,COFINS e CSLL dos proced.', 'AOCALC_PIS_COFINS_CSLL_PROCED', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (177, 'Indica se será calculado PISPASEP,COFINS e CSLL dos insumos', 'AOCALC_PIS_COFINS_CSLL_INSU', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (178, 'Indica se deve ser calculado imposto único', 'AOCALC_IMPOSTO_UNICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (179, 'Código imposto único', 'CDIMPOSTO_UNICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (180, 'Classificação imposto único', 'CDCLASSIFIC_IMPOSTO_UNICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (181, 'Tipo de classificação do estabelecimento de saúde', 'TPCLASSIFIC_ESTABELECIMENTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (182, 'Código Nacional de Estabelecimento de Saúde', 'CDCNES', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (183, 'Nome do diretor técnico da entidade de saúde', 'NODIRETOR_TEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (184, 'Número de registro na ANS da Unidade Origem', 'NRREGISTRO_ANS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (185, 'Data de início da contratualização', 'DTINI_CONTRATUALIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (186, 'Tipo de Disponibilidade do Serviço', 'TPDISPONIBILIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (187, 'Indica se o prestador é uma cooperativa médica', 'AOCOOP_MEDICA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (188, 'Indica se prestador pertence a rede de acidente de trabalho', 'AOREDE_ACIDENTE_TRABALHO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (189, 'Identifica se o prestador pratica tabela própria', 'AOPRATICA_TAB_PROPRIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (190, 'Identifica o perfil assistencial do hospital.', 'NRPERFIL_ASSIT_HOSPITAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (191, 'Indica o tipo de produto que o prestador atende', 'TPPRODUTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (192, 'Indica se o prestador aparece ou não no Guia Médico', 'AOIND_PUBLIC_GUIA_MEDICO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (193, 'Sigla do Conselho Profissional do Diretor Técnico', 'SGCONSELHO_DIRETOR_TEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (194, 'Número do conselho do Diretor Técnico da entidade de saúde', 'CDCONSELHO_DIRETOR_TEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (195, 'Sigla da UF do Conselho Profissinal do Diretor Técnico', 'CDESTADO_CONSELHO_DIRETOR_TEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (196, 'Tipo de Rede conforme Manual do Intercâmbio Nacional', 'TPREDE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (197, 'Código do vínculo', 'NRVINCULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (198, 'Código da especialidade', 'NRESPECIALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (199, 'Indica se a especialidade é a principal ou não', 'AOESPEC_PRINCIPAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (200, 'Indica se esta especialidade será considerada ao vínculo', 'AOCONSID_QTD_VINCULO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (201, 'Registro da especialidade no Conselho Federal de Medicina', 'CDREG_ESPECIALIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (202, 'Tipo de contratualização', 'TPCONTRATUALIZACAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (203, 'Indica se possui Registro de Certificado de Especialista', 'AOPOSSUI_REG_CERTIFIC_ESPEC', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (204, 'Hora entrada manhã', 'HRENTRADA_MANHA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (205, 'Hora saída manhã', 'HRSAIDA_MANHA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (206, 'Hora entrada tarde', 'HRENTRADA_TARDE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (207, 'Hora saída tarde', 'HRSAIDA_TARDE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (208, 'Indica se trabalha segunda-feira', 'AOTRABALHA_SEGUNDA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (209, 'Hora entrada manhã segunda-feira', 'HRENTRADA_MANHA_SEG', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (210, 'Hora saída manhã segunda-feira', 'HRSAIDA_MANHA_SEG', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (211, 'Hora entrada tarde segunda-feira', 'HRENTRADA_TARDE_SEG', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (212, 'Hora saída tarde segunda-feira', 'HRSAIDA_TARDE_SEG', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (213, 'Indica se trabalha terça-feira', 'AOTRABALHA_TERCA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (214, 'Hora entrada manhã terça-feira', 'HRENTRADA_MANHA_TER', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (215, 'Hora saída manhã terça-feira', 'HRSAIDA_MANHA_TER', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (216, 'Hora entrada tarde terça-feira', 'HRENTRADA_TARDE_TER', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (217, 'Hora saída tarde terça-feira', 'HRSAIDA_TARDE_TER', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (218, 'Indica se trabalha quarta-feira', 'AOTRABALHA_QUARTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (219, 'Hora entrada manhã quarta-feira', 'HRENTRADA_MANHA_QUA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (220, 'Hora saída manhã quarta-feira', 'HRSAIDA_MANHA_QUA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (221, 'Hora entrada tarde quarta-feira', 'HRENTRADA_TARDE_QUA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (222, 'Hora saída tarde quarta-feira', 'HRSAIDA_TARDE_QUA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (223, 'Indica se trabalha quinta-feira', 'AOTRABALHA_QUINTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (224, 'Hora entrada manhã quinta-feira', 'HRENTRADA_MANHA_QUI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (225, 'Hora saída manhã quinta-feira', 'HRSAIDA_MANHA_QUI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (226, 'Hora entrada tarde quinta-feira', 'HRENTRADA_TARDE_QUI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (227, 'Hora saída tarde quinta-feira', 'HRSAIDA_TARDE_QUI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (228, 'Indica se trabalha sexta-feira', 'AOTRABALHA_SEXTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (229, 'Hora entrada manhã sexta-feira', 'HRENTRADA_MANHA_SEX', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (230, 'Hora saída manhã sexta-feira', 'HRSAIDA_MANHA_SEX', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (231, 'Hora entrada tarde sexta-feira', 'HRENTRADA_TARDE_SEX', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (232, 'Hora saída tarde sexta-feira', 'HRSAIDA_TARDE_SEX', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (233, 'Indica se trabalha sábado', 'AOTRABALHA_SABADO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (234, 'Hora entrada manhã sábado', 'HRENTRADA_MANHA_SAB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (235, 'Hora saída manhã sábado', 'HRSAIDA_MANHA_SAB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (236, 'Hora entrada tarde sábado', 'HRENTRADA_TARDE_SAB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (237, 'Hora saída tarde sábado', 'HRSAIDA_TARDE_SAB', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (238, 'Indica se trabalha domingo', 'AOTRABALHA_DOMINGO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (239, 'Hora entrada manhã domingo', 'HRENTRADA_MANHA_DOM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (240, 'Hora saída manhã domingo', 'HRSAIDA_MANHA_DOM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (241, 'Hora entrada tarde domingo', 'HRENTRADA_TARDE_DOM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (242, 'Hora saída tarde domingo', 'HRSAIDA_TARDE_DOM', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (243, 'Indica se o endereço em questão recebe correspondência', 'AORECEBE_CORRESPONDENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (244, 'Tipo de endereço', 'TPENDERECO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (245, 'Número de leitos totais exceto UTI', 'NRLEITOS_TOTAIS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (246, 'Número de leitos contratados', 'NRLEITOS_CONTRATADOS', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (247, 'Número de leitos de psiquiatria', 'NRLEITOS_PSIQUIATRIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (248, 'Número de leitos UTI - adulto', 'NRLEITOS_UTI_ADULTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (249, 'Número de leitos UTI - neonatal', 'NRLEITOS_UTI_NEONATAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (250, 'Número de leitos UTI - pediatria', 'NRLEITOS_UTI_PEDIATRIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (251, 'Complemento do endereço', 'COMPLEMENTO_ENDERECO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (252, 'Indica se o endereço é de uma filial', 'AOENDERECO_FILIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (253, 'Número do CGC/CPF da filial', 'CGC_CPF_FILIAL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (254, 'Código da Cidade', 'CDCIDADE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (255, 'Código do Imposto', 'CDIMPOSTO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (256, 'Data da Vigência Inicial do Imposto', 'DTVIGENCIA_INI', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (257, 'Data da Vigência Final do Imposto', 'DTVIGENCIA_FIN', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (258, 'Sinal de valor mínimo (0 -Vl. positivo /1 -Vl. negativo)', 'NRSINAL_VL_MIN', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (259, 'Valor Mínimo de Retenção de Impostos', 'VLMIN_RETENCAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (260, 'Número da inscrição do contratante', 'NRINSC_CONTRATANTE', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (261, 'Número da Proposta', 'NRPROPOSTA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (262, 'Código do Grau de Parentesco', 'NRGRAU_PARENTESCO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (263, 'Informa se o beneficiário é o responsável', 'AORESPONSAVEL', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (264, 'Data de inclusão do beneficiário no Plano', 'DTINCLU_PLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (265, 'Data de exclusão do beneficiário no Plano', 'DTEXCLU_PLANO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (266, 'Indica se possui Carência', 'AOCARENCIA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (267, 'Código do funcionário na Empresa', 'CDFUNCIONARIO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (268, 'Data de Admissão na Empresa', 'DTADMISSAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (269, 'Número do CPF', 'CPF', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (270, 'Indica se a Taxa de Inscrição será cobrada na Fatura', 'AOTAXA_INSCRICAO', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (271, 'Padrão de Cobertura', 'CDPADRAO_COBERTURA', 'S', 'S', 'MG');
insert into REM_INFORMACAO (CDINFORMACAO, TXDESCRICAO, TXMETODO, AOENVIO, AORETORNO, CDGRUPO_INFORMACAO)
values (272, 'Informações Específicas 1', 'TXINF_ESPECIFICAS1', 'S', 'S', 'MG');
set feedback on
set define on
prompt Done.
