-- 08.7) Criação do Destinatário da Geração

insert into REM_DESTINATARIO (CDDESTINATARIO, NODESTINATARIO, TXCONTATOS)
values ('3000', 'Migração Unicoo X TOTVS 12', '');
COMMIT;

-- 08.8) Criação do Grupo de Informação

insert into REM_GRUPO_INFORMACAO (CDGRUPO_INFORMACAO, NOGRUPO_INFORMACAO)
values ('MG', 'MIGRACAO TOTVS 12');

COMMIT;


-- 08.11) Criação do Layout de Prestador

/*
  Inserindo na REM_ARQUIVO
*/

insert into rem_arquivo (NRSEQUENCIA, CDPORTADOR, TPARQUIVO, AOLOCALIZACAO, NOARQUIVO_BANCO, NOARQUIVO_INTERNO, NRULTIMA_GERACAO, DTULTIMA_GERACAO, CDGRUPO_INFORMACAO, TXDESCRICAO, CHAR_SEPARADOR, NOLAY_OUT, CDOPERACAO_COBRANCA, TPREGISTRO_LOTE, NRPOSICAO_TIPO_REG, NRPOSICAO_SEGMENTO, TPREGISTRO_TRAILER_LOTE, FORMATOARQUIVO, CDASSINATURA_DIGITAL)
values (9151, null, 'E', 'C:\TEMP', '', '', null, null, 'MG', 'MIGRACAO - PRESTADORES', '', '', '', '', null, null, '', 'ANSI', '');

commit;


/*
  Inserindo na REM_GERACAO_ARQUIVO 
*/

insert into rem_geracao_arquivo (NRGERACAO, NRSEQUENCIA_ARQUIVO, TXSQL_CAMPOS, TXSQL_TABELAS, TXSQL_RELACIONAMENTOS, TXDESCRICAO_GERACAO, CDDESTINATARIO, CDPRODUTO, NOLOGUSADO, NOPROCEDURE, VLPARAMETRO)
values (9151, 9151, 'SELECT * FROM V_MIGRACAO_PRESTADOR
ORDER BY NRSEQUENCIAL, ORDEM_1', '', '', 'MIGRACAO - PRESTADOR', '3000', '', '', NULL, '');

commit;

/*
  Inserindo na REM_PARAMETRO_GERACAO
*/

insert into rem_parametro_geracao (NRGERACAO, CDPARAMETRO, TXINFORMACAO, TXOBSERVACAO, CDTIPO_DADO, NRSEQUENCIA, TPPARAMETRO, AOOBRIGATORIO, VLPARAMETRO)
values (9151, 'PNOSENDER', 'SENDER', '', 'C', 1, 'P', 'N', 'TAS97FMg');

commit;

/*
  Inserindo na REM_REGISTRO 
*/

insert into rem_registro (NRSEQUENCIA, TPREGISTRO, CDCAMPO_QUEBRA, CDCOMPO_CONDICAO, AOCONDICAO, TXCONDICAO, CDCAMPO_CONDICAO, IDREGISTRO, CDCAMPO_QUEBRA_LOTE, IGNORA_REG_RETORNO, NRLIMITEREG)
values (9151, '1', 'NRSEQUENCIAL', '', '', '', '', 'Prestadores', '', '', '');
insert into rem_registro (NRSEQUENCIA, TPREGISTRO, CDCAMPO_QUEBRA, CDCOMPO_CONDICAO, AOCONDICAO, TXCONDICAO, CDCAMPO_CONDICAO, IDREGISTRO, CDCAMPO_QUEBRA_LOTE, IGNORA_REG_RETORNO, NRLIMITEREG)
values (9151, '2', '', '', '=', '2', 'ORDEM_1', 'Prest. Vinc. Espec.', '', 'N', '0');
insert into rem_registro (NRSEQUENCIA, TPREGISTRO, CDCAMPO_QUEBRA, CDCOMPO_CONDICAO, AOCONDICAO, TXCONDICAO, CDCAMPO_CONDICAO, IDREGISTRO, CDCAMPO_QUEBRA_LOTE, IGNORA_REG_RETORNO, NRLIMITEREG)
values (9151, '3', '', '', '=', '3', 'ORDEM_1', 'Endereços do Prest.', '', 'N', '0');

commit;
