prompt PL/SQL Developer import file
prompt Created on quinta-feira, 28 de abril de 2016 by totvs
set feedback off
set define off
prompt Loading REM_CAMPO...
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1, 1, 'Tipo Registro', 'T', '1', null, '3', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 2, 5, 'Código Unidade', 'C', null, null, '3', 116, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 6, 13, 'Código Prestador', 'C', null, null, '3', 117, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 14, 53, 'Reservado', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 54, 65, 'Nome Abreviado', 'C', null, null, '1', 4, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 66, 66, 'Tipo Pessoa', 'C', null, null, '1', 2, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 67, 68, 'Grupo Prestador', 'C', null, null, '3', 119, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 69, 69, 'Médico?', 'C', null, null, '1', 120, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 70, 70, 'Credenciado?', 'C', null, null, '1', 121, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 71, 74, 'Unidade Seccional', 'C', null, null, '3', 122, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 75, 79, 'Conselho', 'C', null, null, '1', 123, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 80, 81, 'UF Conselho', 'C', null, null, '1', 124, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 82, 89, 'Registro CRM', 'C', null, null, '3', 125, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 90, 98, 'Código Fornecedor', 'C', null, null, '3', 126, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 99, 138, 'Endereço', 'C', null, null, '1', 8, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 139, 153, 'Bairro', 'C', null, null, '1', 9, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 154, 159, 'Código da Cidade', 'C', null, null, '3', 254, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 160, 167, 'CEP', 'C', null, null, '3', 12, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 168, 169, 'UF', 'C', null, null, '1', 11, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 170, 181, 'Campo Reservado', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 182, 193, 'Campo Reservado', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 194, 201, 'Data Inclusão Prestador', 'C', null, null, '1', 127, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 202, 209, 'Data Exclusão Prestador', 'C', null, null, '1', 128, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 210, 210, 'Sexo', 'C', null, null, '1', 7, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 211, 218, 'Dt. Nascimento ou Fundação', 'C', null, null, '1', 5, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 219, 222, 'Inscrição prestador na unidade', 'C', null, null, '3', 129, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 223, 224, 'Situação Sindical', 'C', null, null, '1', 130, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 225, 236, 'Fator de Produtividade Prestador', 'C', null, null, '4', 131, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 237, 237, 'Possui alvará?', 'C', null, null, '1', 132, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 238, 238, 'Possui registro INSS?', 'C', null, null, '1', 133, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 239, 239, 'Possui Diploma?', 'C', null, null, '1', 134, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 240, 242, 'Especialidade Residência', 'C', null, null, '3', 135, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 243, 245, 'Especialidade Título', 'C', null, null, '3', 136, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 246, 246, 'Recebe Malote?', 'C', null, null, '1', 137, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 247, 247, 'Possui Vínculo Empregatício?', 'C', null, null, '1', 138, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 248, 253, 'Último mês INSS', 'C', null, null, '3', 139, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 254, 261, 'Campo em branco', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 262, 266, 'Ramal 1', 'C', null, null, '1', 15, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 267, 271, 'Ramal 2', 'C', null, null, '1', 17, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 272, 290, 'CGC/CPF', 'C', null, null, '1', 3, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 291, 291, 'Representa uma Unidade?', 'C', null, null, '1', 140, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 292, 293, 'Código Horário de Urgência', 'C', null, null, '3', 141, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 294, 294, 'Recolhe INSS?', 'C', null, null, '1', 142, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 295, 295, 'Recolhe Participação?', 'C', null, null, '1', 143, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 296, 371, 'Observação 1', 'C', null, null, '1', 144, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 372, 447, 'Observação 2', 'C', null, null, '1', 145, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 448, 523, 'Observação 3', 'C', null, null, '1', 146, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 524, 524, 'Calcular Imposto de Renda?', 'C', null, null, '1', 147, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 525, 526, 'Índice IRRF', 'C', null, null, '3', 148, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 527, 532, 'Campo em Branco', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 533, 533, 'Calcular adiantamento?', 'C', null, null, '1', 149, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 534, 541, 'Data Cálculo Adiantamento', 'C', null, null, '1', 150, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 542, 543, 'Número de Dependentes', 'C', null, null, '3', 151, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 544, 544, 'Pagamento RH?', 'C', null, null, '1', 152, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 545, 594, 'E-mail', 'C', null, null, '1', 87, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 595, 606, 'Tipo de Fluxo', 'C', null, null, '1', 153, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 607, 611, 'Imposto', 'C', null, null, '1', 255, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 612, 616, 'Classificação do Imposto ', 'C', null, null, '1', 155, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 617, 627, 'Número do PIS/PASEP', 'C', null, null, '3', 156, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 628, 641, 'Número Inscrição INSS', 'C', null, null, '1', 157, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 642, 642, 'Divide Horário?', 'C', null, null, '1', 158, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 643, 643, 'Calcula COFINS?', 'C', null, null, '1', 159, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 644, 644, 'Calcula PIS/PASEP?', 'C', null, null, '1', 160, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 645, 645, 'Calcula CSLL?', 'C', null, null, '1', 161, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 646, 650, 'Código Imposto COFINS', 'C', null, null, '1', 162, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 651, 655, 'Código Imposto PIS/PASEP', 'C', null, null, '1', 163, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 656, 660, 'Código Imposto CSLL', 'C', null, null, '1', 164, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 661, 665, 'Classificação Imposto COFINS', 'C', null, null, '1', 165, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 666, 670, 'Classificação Imposto PIS/PASEP', 'C', null, null, '1', 166, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 671, 675, 'Classificação Imposto CSLL', 'C', null, null, '1', 167, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 676, 680, 'Código Imposto INSS', 'C', null, null, '1', 168, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 681, 685, 'Classificação Imposto INSS', 'C', null, null, '1', 169, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 686, 686, 'Calcula ISS?', 'C', null, null, '1', 170, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 687, 691, 'Código Imposto ISS', 'C', null, null, '1', 171, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 692, 696, 'Classificação Imposto ISS', 'C', null, null, '1', 172, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 697, 697, 'Deduzir ISS da Produção?', 'C', null, null, '1', 173, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 698, 700, 'Dias de Validade para Reconsulta', 'C', null, null, '3', 174, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 701, 705, 'Portador', 'C', null, null, '3', 82, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 706, 706, 'Modalidade', 'C', null, null, '3', 83, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 707, 709, 'Código Banco', 'C', null, null, '3', 84, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 710, 717, 'Número da Agência', 'C', null, null, '1', 85, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 718, 737, 'Número da Conta Corrente', 'C', null, null, '1', 86, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 738, 739, 'Dígito da Agência', 'C', null, null, '1', 107, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 740, 741, 'Dígito da Conta Corrente', 'C', null, null, '1', 108, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 742, 744, 'Forma de Pagamentto', 'C', null, null, '1', 175, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 745, 745, 'Calcula PIS,COFINS,CSLL de Proc.?', 'C', null, null, '1', 176, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 746, 746, 'Calcula PIS,COFINS,CSLL de Insumos?', 'C', null, null, '1', 177, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 747, 747, 'Calcula Imposto Unico?', 'C', null, null, '1', 178, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 748, 752, 'Código Imposto Unico', 'C', null, null, '1', 179, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 753, 757, 'Classificação Imposto Unico', 'C', null, null, '1', 180, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 758, 758, 'Tipo Classificação Estabelecimento', 'C', null, null, '1', 181, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 759, 765, 'CNES', 'C', null, null, '1', 182, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 766, 805, 'Nome do Diretor Técnico', 'C', null, null, '1', 183, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 806, 813, 'Reservado', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 814, 819, 'Registro na ANS', 'C', null, null, '3', 184, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 820, 827, 'Data Início Constratualização', 'C', null, null, '1', 185, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 828, 867, 'Natureza Doc. Identificação', 'C', null, null, '1', 109, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 868, 881, 'Número Doc.Identificação', 'C', null, null, '1', 23, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 882, 911, 'Orgão Emissor Doc. Ident.', 'C', null, null, '1', 110, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 912, 931, 'País Emissor Doc. Ident.', 'C', null, null, '1', 111, null, null, null, null, null, null, null, null);
prompt 100 records committed...
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 932, 933, 'Estado Emissor Doc. Ident.', 'C', null, null, '1', 112, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 934, 941, 'Data Emissão DOc. Ident.', 'C', null, null, '1', 113, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 942, 981, 'Nacionalidade', 'C', null, null, '1', 114, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 982, 1001, 'Telefone 1', 'C', null, null, '1', 14, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1002, 1021, 'Telefone 2', 'C', null, null, '1', 16, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1022, 1022, 'Tipo de Disponibilidade', 'C', null, null, '1', 186, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1023, 1023, 'Cooperativa Médica?', 'C', null, null, '1', 187, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1024, 1024, 'Rede Acidente de Trabalho?', 'C', null, null, '1', 188, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1025, 1025, 'Pratica Tabela Própria?', 'C', null, null, '1', 189, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1026, 1027, 'Perfil Assist. Hospital', 'C', null, null, '3', 190, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1028, 1028, 'Tipo Produto', 'C', null, null, '3', 191, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1029, 1029, 'Ind. Pub. Guia Médico', 'C', null, null, '1', 192, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1030, 1041, 'Sigla Conselho Diretor Téc.', 'C', null, null, '1', 193, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1042, 1056, 'Número Conselho Diretor Téc.', 'C', null, null, '1', 194, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1057, 1058, 'UF Conselho Diretor Téc.', 'C', null, null, '1', 195, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1059, 1059, 'Tipo Rede', 'C', null, null, '3', 196, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1060, 1060, 'Sistema NOTIVISA', 'C', null, null, '1', 497, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1061, 1061, 'Sistema QUALISS', 'C', null, null, '1', 496, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1062, 1071, 'Nr. Reg. Especialista 1', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1072, 1081, 'Nr. Reg. Especialista 2', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1082, 1087, 'Nr. Leitos Hospital-dia', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1088, 1137, 'Endereco WEB', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1138, 1177, 'Nome Fantasia', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1178, 1247, 'Nome Prestador', 'C', null, null, '1', 118, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1248, 1248, 'Divulga ANS', 'T', 'N', null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1249, 1249, 'Residencia reconhecida MEC', 'T', 'S', null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1250, 1250, 'Envia manutencao WSD-TISS', 'T', 'N', null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '1', 1251, 1251, 'Envia Cadu', 'C', null, null, '1', 498, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 1, 1, 'Tipo Registro', 'T', '2', null, '3', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 2, 3, 'Código Vínculo', 'C', null, null, '3', 197, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 4, 6, 'Código da Especialidade', 'C', null, null, '3', 198, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 7, 7, 'Especialidade Principal?', 'C', null, null, '1', 199, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 8, 8, 'Considera Qtd. Vínculo?', 'C', null, null, '1', 200, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 9, 18, 'Registro Especialidade', 'C', null, null, '1', 201, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 19, 19, 'Tipo Contratualização', 'C', null, null, '1', 202, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 20, 20, 'Possui Reg. Certificação Espec.?', 'C', null, null, '1', 203, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 21, 30, 'Registro Especialidade 2', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 31, 31, 'Ind. Ginec. e/ou Obstret.', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 32, 34, 'Cod.Tit.Cert.Esp.Medica', 'T', null, null, '1', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 35, 42, 'Inicio Vlidade', 'C', null, null, '1', 499, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '2', 43, 50, 'Fim validade', 'C', null, null, '1', 500, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 1, 1, 'Tipo Registro', 'T', '3', null, '3', null, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 2, 41, 'Endereço', 'C', null, null, '1', 470, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 42, 56, 'Bairro', 'C', null, null, '1', 474, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 57, 62, 'Cidade', 'C', null, null, '3', 472, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 63, 70, 'CEP', 'C', null, null, '1', 475, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 71, 72, 'UF', 'C', null, null, '1', 467, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 73, 84, 'Telefone 1', 'C', null, null, '1', 468, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 85, 96, 'Telefone 2', 'C', null, null, '1', 477, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 97, 101, 'Ramal 1', 'C', null, null, '1', 476, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 102, 106, 'Ramal 2', 'C', null, null, '1', 471, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 107, 110, 'Hora Entrada Manhã', 'C', null, null, '1', 204, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 111, 114, 'Hora Saída Manhã', 'C', null, null, '1', 205, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 115, 118, 'Hora Entrada Tarde', 'C', null, null, '1', 206, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 119, 122, 'Hora Saída Tarde', 'C', null, null, '1', 207, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 123, 123, 'Trabalha Segunda?', 'C', null, null, '1', 208, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 124, 127, 'Hora Entrada Manhã Seg.', 'C', null, null, '1', 209, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 128, 131, 'Hora Saída Manhã Seg.', 'C', null, null, '1', 210, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 132, 135, 'Hora Entrada Tarde Seg.', 'C', null, null, '1', 211, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 136, 139, 'Hora Saída Tarde Seg.', 'C', null, null, '1', 212, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 140, 140, 'Trabalha Terça?', 'C', null, null, '1', 213, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 141, 144, 'Hora Entrada Manhã Ter.', 'C', null, null, '1', 214, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 145, 148, 'Hora Saída Manhã Ter.', 'C', null, null, '1', 215, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 149, 152, 'Hora Entrada Tarde Ter.', 'C', null, null, '1', 216, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 153, 156, 'Hora Saída Tarde Seg.', 'C', null, null, '1', 217, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 157, 157, 'Trabalha Quarta?', 'C', null, null, '1', 218, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 158, 161, 'Hora Entrada Manhã Qua.', 'C', null, null, '1', 219, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 162, 165, 'Hora Saída Manhã Qua.', 'C', null, null, '1', 220, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 166, 169, 'Hora Entrada Tarde Qua.', 'C', null, null, '1', 221, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 170, 173, 'Hora Saída Tarde Qua.', 'C', null, null, '1', 222, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 174, 174, 'Trabalha Quinta?', 'C', null, null, '1', 223, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 175, 178, 'Hora Entrada Manhã Qui.', 'C', null, null, '1', 224, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 179, 182, 'Hora Saída Manhã Qui.', 'C', null, null, '1', 225, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 183, 186, 'Hora Entrada Tarde Qui.', 'C', null, null, '1', 226, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 187, 190, 'Hora Saída Tarde Qui.', 'C', null, null, '1', 227, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 191, 191, 'Trabalha Sexta?', 'C', null, null, '1', 228, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 192, 195, 'Hora Entrada Manhã Sex.', 'C', null, null, '1', 229, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 196, 199, 'Hora Saída Manhã Sex.', 'C', null, null, '1', 230, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 200, 203, 'Hora Entrada Tarde Sex.', 'C', null, null, '1', 231, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 204, 207, 'Hora Saída Tarde Sex.', 'C', null, null, '1', 232, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 208, 208, 'Trabalha Sábado?', 'C', null, null, '1', 233, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 209, 212, 'Hora Entrada Manhã Sab.', 'C', null, null, '1', 234, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 213, 216, 'Hora Saída Manhã Sab.', 'C', null, null, '1', 235, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 217, 220, 'Hora Entrada Tarde Sab.', 'C', null, null, '1', 236, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 221, 224, 'Hora Saída Tarde Sab.', 'C', null, null, '1', 237, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 225, 225, 'Trabalha Domingo?', 'C', null, null, '1', 238, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 226, 229, 'Hora Entrada Manhã Dom.', 'C', null, null, '1', 239, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 230, 233, 'Hora Saída Manhã Dom.', 'C', null, null, '1', 240, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 234, 237, 'Hora Entrada Tarde Dom.', 'C', null, null, '1', 241, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 238, 241, 'Hora Saída Tarde Dom.', 'C', null, null, '1', 242, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 242, 242, 'Recebe Malote?', 'C', null, null, '1', 469, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 243, 243, 'Recebe Correspondência?', 'C', null, null, '1', 243, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 244, 244, 'Tipo Endereço', 'C', null, null, '3', 244, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 245, 251, 'CNES', 'C', null, null, '1', 473, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 252, 257, 'Número Leitos Totais', 'C', null, null, '3', 245, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 258, 263, 'Número Leitos Contratados', 'C', null, null, '3', 246, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 264, 269, 'Número Leitos Psiquiatria', 'C', null, null, '3', 247, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 270, 275, 'Número Leitos UTI Adulto', 'C', null, null, '3', 248, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 276, 281, 'Número Leitos UTI Neonatal', 'C', null, null, '3', 249, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 282, 287, 'Número Leitos UTI Pediatria', 'C', null, null, '3', 250, null, null, null, null, null, null, null, null);
prompt 200 records committed...
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 288, 302, 'Complemento Endereço', 'C', null, null, '1', 251, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 303, 303, 'Endereço Filial?', 'C', null, null, '1', 252, null, null, null, null, null, null, null, null);
insert into REM_CAMPO (NRSEQUENCIA, TPREGISTRO, NRPOSICAO_INICIAL, NRPOSICAO_FINAL, DESCRICAO, TPCONTEUDO, TXCONTEUDO, TXINFORMACAO, CDMASCARA, CDINFORMACAO, AOCONDICAO, TXCONDICAO, AOABREVIA, NOLAY_OUT, TXMASCARA, AOSOMATORIA, CDFORMULA, NRMATRIZ)
values (9151, '3', 304, 322, 'Número CGC/CPF da Filial', 'C', null, null, '1', 253, null, null, null, null, null, null, null, null);
prompt 203 records loaded
set feedback on
set define on
prompt Done.
