declare
  
    CURSOR C_TABLES IS
      SELECT 'TRUNCATE TABLE ' || T.OWNER || '.' || T.TABLE_NAME COMANDO
        FROM TM_TABELAS_MOVIMENTACAO T;
  
  BEGIN
    FOR C IN C_TABLES LOOP
    
      EXECUTE IMMEDIATE C.COMANDO;
    
    END LOOP;
  
  END;
