-- EXECUTAR P_CARGA_INICIAL_CLIENTE (MONTA TI_PESSOA e TI_CONTROLE_INTEGRACAO, TEMPORARIAS USADAS PELOS DEMAIS PROCESSOS DA MIGRACAO DO UNICOO PARA TOTVS12)
begin
  pck_ems506unicoo.P_CARGA_INICIAL_CLIENTE;
end;
--select count(*) from ti_cliente--273147
